### PR TITLE
New Publisher: New features and preparations for new standalone publisher

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Brief description
Added few required features in new publisher and prepare it to be usable in standalone publisher.

## Changes
- extended creator dialog
    - has context selection (creator can tell if it make sense)
    - has widget where creator can define "pre-create" attributes for which can be used same objects as for instance attributes
        - this can be used for any Creator's specific inputs that may be needed before the creation
        - best example is `Use selection` which is not anymore in default create dialog
- create context and Publisher can work even asset and task is not defined (in global context `AVALON_ASSET` and `AVALON_TASK`)
    - this is needed for new standalone publisher
- added new attribute definitions
    - boolean - simple True/False
    - file input - can define filters of file types if accepts folder path or specific extensions and if output is single file or multiple files
        - this is 50% finished (missing filtering of single file input and some UI details)
    - UI specific attributes - Label and Separator
- Assets widget and Tasks widget were modigied to be possible easily change how their models are created and handled
    - Assets widget has button to set current context which is visible only if there is current context (when at least `AVALON_ASSET` is set)
- renamed method `get_attribute_defs` to `get_instance_attr_defs` on creator class
- moved few widgets from publisher to utils as are already used at multiple places
- modified NiceCheckbox background color
- reset of publisher can be skipped
    - new standalone publisher will need to select project before publisher is reset
- fixed smaller resize issues
- publish attributes are not duplicated anymore

### How create dialog looks now.
- Left side contain context widgets (asset/task)
- Middle contain creators list and variant input field
- Right creator's pre-create attributes (can be empty)

## Example screenshot 1
image

**Examples**
1. Context widget is disabled because the selected creator defined that before creation selection of context does not make sense
2. Boolean attribute example
3. Separator attribute example
4. Label attribute example
5. Single file attribute example
6. Multi file attribute example
7. Change of checkbox background color

## Example screenshot 2
Second creator have enabled context change but does not have any pre-create attributes.
image

## How to test
At this moment the easiest is to run `testhost` (script `~/openpype/hosts/testhost/run_publish.py` requires few changes).
You can play with the 2 creator which are there now to test different cases.

### CODE REVIEW

**Comment by mkolar** [comment]
Task linked: [OP-2429 Publisher: Preparations before standalone publisher](https://app.clickup.com/t/6658547/OP-2429)

**Review by mkolar — CHANGES_REQUESTED** [review]
I'm thinking that we should put some explainer text on the right side for creators that don't define any attributes to edit. The empty space makes it feel like something is missing :).

Maybe just 
```
This creator had no configurable options.
```
In the middle of the space

**Comment by iLLiCiTiT** [comment]
> I'm thinking that we should put some explainer text on the right side for creators that don't define any attributes to edit. The empty space makes it feel like something is missing :).

Added

image

**Comment by mkolar** [comment]
You copied my grammar mistake :D. It should be `This creator has no configurable options.`

**Comment by iLLiCiTiT** [comment]
> You copied my grammar mistake

It's not a mistake. It's an easter egg :) Fixed

**Review by mkolar — APPROVED** [review]

**Pull request merged**
