### PR TITLE
Settings for Nuke IncrementScriptVersion

### PR DESCRIPTION
**Pull request by kalisp**
Plugin for increasing workfile version is now configurable, optional and families could be selected. (Default setting as per current configuration in the plugin.)

Closes https://app.clickup.com/t/6658547/PYPE-1839

On client side Setting must be set as they request!

Screenshot 2021-09-17 130341

### CODE REVIEW

**Comment by mkolar** [comment]
Task linked: [PYPE-1839 Workfile Version Increment Upon Publishing](https://app.clickup.com/t/6658547/PYPE-1839)

**Comment by mkolar** [comment]
To be honest I'm a bit confused as to why we have that filter. The plugin is supposed to only work on workfiles by definition, so why are we filtering render.local and render.farm?

Wouldn't it be enough to have `active` and `optional` triggers here?

**Comment by jakubjezek001** [comment]
There might be a opinion about this workflow from some productions. Sort of:
`What if we don't want to increase version of workfile after 'prerender' publishes?` or 
`We would like to keep versioning as less as possible for our client would like to have version synchronized to their review cycle`. In that case prerender publishing (and lot of studios already exchange this for deadline submitter) will be heavily incressing the version of workfile in case we will remove the families filter.

**Comment by mkolar** [comment]
>In that case prerender publishing (and lot of studios already exchange this for deadline submitter) will be heavily increasing the version of workfile in case we will remove the families filter.

Fair enough. The question is then if this is good enough. because if I'm sending to the farm (prerender or render), I thought we require publish of the workfiles to prevent accidental changes to it during the rendering. Which in turn would raise the version anyway.

**Comment by jakubjezek001** [comment]
Yes, that is right, it is broken anyway as we will need to have workfile in context all the time and in that case the plugin will rise it all the time even `prerender` and its derivate families will be present.. 

We have to introduce something more solid, based on blacklisting it on `taskType` and `family` manner. 

Or what are yours sugestions?

**Comment by jakubjezek001** [comment]
also another alternative would be to introduce something like snapshots of one version. So this would be always publishing `workfile` even we would publish `geo` or `camera` or `gizmo`. Only difference would be it would not increse `v###` but it would add suffix with generated hash something like `workfilename_v002_oxw2o.nk`. 

You might ask, why would we do this? This way we would keep strickty the workfile versioning tightli synced with reviewing cycle and allow separating workifle per publish. 

This is just an idea..

**Comment by kalisp** [comment]
I could rewrite plugin to:
- if workfile is published AND any of the configured family is published too, version workfile up
- if workfile is not published (local render, as I am guessing that farm render forces publishing of workfile), do not version up, even if any configured family is being published (eg. I am publishing `prerender` locally, but I dont want to version up workfile.)

**Comment by kalisp** [comment]
Removed 'families' configuration

**Review by jakubjezek001 — APPROVED** [review]

**Review by 64qam — APPROVED** [review]

**Pull request merged**
