### PR TITLE
OpenPype: Support for Docker

### PR DESCRIPTION
**Pull request by antirotor**
## Feature

This is adding support for Docker build of OpenPype. Currenly only for Linux.

### How to use it:

Just run:
```sh
sudo ./tools/build_docker.sh
```
and if all goes well, you will have OpenPype in `./build`. No need to install any dependencies. It will create image `pypeclub/openpype` and tag it with current version parsed from sources.

We also have published OpenPype Docker Image. To get it, you can:
```sh
docker pull pypeclub/openpype:latest
```
To run OpenPype from Docker Container:

```sh
sudo docker run -it pypeclub/openpype:latest /opt/openpype/build/exe.linux-x86_64-3.7/openpype_console
```
but it doesn't make much sense now, except perhaps for ftrack event server, but for that we need more configuration. It is possible to run OpenPype UI from container on Linux running X11 by setting correct environment variables for Qt and mounting project volumes so it can access files, but more work needs to be done on this front.

You can push new OpenPype image to Docker  by:

```sh
pypeVersion="3.2.1" # or parsed from sources, ...
sudo docker push pypeclub/openpype:$pypeVersion
```

### CODE REVIEW

**Comment by antirotor** [comment]
we can link it with GitHub then:
https://docs.docker.com/docker-hub/builds/

**Comment by kalisp** [comment]
`docker pull pypeclub/openpype:latest` didn't work for me:
```Error response from daemon: manifest for pypeclub/openpype:latest not found: manifest unknown: manifest unknown```

`docker pull pypeclub/openpype:3.0.0-beta` which is on dockerhub did

**Comment by kalisp** [comment]
And it failed when I tried to run it:
Screenshot 2021-04-14 090200

**Comment by antirotor** [comment]
> And it failed when I tried to run it:
> Screenshot 2021-04-14 090200

running it is not supported as the base image doesn't have GUI at all so it can't even display Igniter. This can be solved in the future on Linux machines, but right now it is used for building OpenPype. You can either build the image (and OpenPype along) with `docker build .` or you can pull the image as you did and run it like:
```
docker run -ti pypeclub/openpype:3.0.0-beta /opt/openpype/tools/build.sh
```
That will build OpenPype inside and you can then copy it out of the container.

**Comment by antirotor** [comment]
> `docker pull pypeclub/openpype:latest` didn't work for me:
> `Error response from daemon: manifest for pypeclub/openpype:latest not found: manifest unknown: manifest unknown`
> 
> `docker pull pypeclub/openpype:3.0.0-beta` which is on dockerhub did

my bad, I thought `latest` tag will be automatically created by Docker.

**Comment by mkolar** [comment]
I get this when trying to run the build

image

**Comment by mkolar** [comment]
Running `./tools/docker_build.sh` on fresh ubuntu with no prep got amazingly far, however failed at copying the build out of the container.
image

**Comment by mkolar** [comment]
viability of this for a developer is questionable though. Good for a single test, but the build is soo long, that it would be faster, to prep the machine manually and then run quick builds from that point on.

**Comment by antirotor** [comment]
> viability of this for a developer is questionable though. Good for a single test, but the build is soo long, that it would be faster, to prep the machine manually and then run quick builds from that point on.

It takes long time just for the first run. Then it caches most of the layers there so it will in fact do only building of venv and build - almost as fast as you would do it on prepared machine. And other point is that you can download whole image from docker and it will just build OpenPype as everything else will already be done in it. So yes, in comparison with with dedicated linux box with already set up build environment it is unnecessary slow process. But to experiment with it on random linux machine so you can repeatedly tweak whatever you want in OpenPype source and you don't need to pollute your environment with tons of large pieces of software you might never use for anything (adding used space to your storage, slowing system updates, etc.). It is also useful for painless experimentation with different versions of required software - for example you can simply change few line in dockerfile to use PyPy python instead of CPython with specific configuration flags - again without messing with your system at all.

**Comment by antirotor** [comment]
Fixed copying and added `patchelf` dependency for `cx_freeze`

**Comment by 64qam** [comment]
After a successful build process, I tried to launch Pype from the build files but got this error.
image (7)

**Review by mkolar — APPROVED** [review]

**Pull request merged**
