### PR TITLE
Nuke: publish existing frames with slate with correct range

### PR DESCRIPTION
**Pull request by jakubjezek001**
## Brief description
Range is correct when published slate from existing frames

## Description
The miscalculation was removed.

## Testing notes:
1. open nuke workfile with slate workflow
2. publish from existing frames
3. notice that frame range is correct and not frame shorter

### CODE REVIEW

**Review by jrsndl — CHANGES_REQUESTED** [review]
The "farm" and "using existing frames" options with slate works with this PR.

Using local publish produces double slate in review files (EXRs are OK). Local publish works with current develop, so I assume fixed farm publish broke local publish.

**Comment by jakubjezek001** [comment]
> The "farm" and "using existing frames" options with slate works with this PR.
> 
> Using local publish produces double slate in review files (EXRs are OK). Local publish works with current develop, so I assume fixed farm publish broke local publish.

Thanks for catching this! Please try it again now.

**Review by jrsndl — CHANGES_REQUESTED** [review]
Local publish makes correct H264 and MXF, but there is one  frame offset in published EXR files. Here the shot has range 997-1006, and slate at 996. The published exr sequence ands up being 997-1007.
image

**Review by jrsndl — APPROVED** [review]
When I exclude Integrate Asset for Nuke host and render + write Families, publishing works fine for local and farm publish, with clean or "dirty" work folder.

I tested h264 and MXF.

**Comment by jakubjezek001** [comment]
@jrsndl please try it one more time. I found some flaws in Farm and Local publishing.

**Review by jrsndl — APPROVED** [review]
Renders have correct range now. I've tested EXR, MXF and H264 outputs with slate, on farm and local renders, with clean and dirty work folder.
I also made a prerender, with review. All good.

I've tested together with OP-3642_Nuke-Local-vs-Farm-Publish-family-inconsistency.
image

**Pull request merged**
