### PR TITLE
MongoDB: backup all collection data

### PR DESCRIPTION
**Pull request by jakubjezek001**
Script possible to run anytime for backing up all collections from defined database.

Required:
mongo tools on PATH

- [x] move script to ./tools
- [x] remove mongodb uri and connect it to environ var instead
- [ ] finalize `run_mongodb_backup.ps1`

### CODE REVIEW

**Comment by jezscha** [comment]
this could also by good for restoring of those data

**Comment by antirotor** [comment]
I would fix those pesky hound issues. Question is about its usage - I suppose this will be used exclusively with OpenPype database, so I would read connection strings as OPENPYPE_MONGO (or from keyring). So you would need to specify only collection to backup. Then maybe we should put it in `./tools`? I always thought of `openpype/scripts` as of something to be called from hosts or other scripts....

**Comment by mkolar** [comment]
This has gotten a bit stale so I'm just reminding that it's here and still waiting for some love. It's not a priority of course. Just felt sorry for the PR :)

**Comment by mkolar** [comment]
we decided to close this for lack of interest

**Pull request closed without merging**
