### PR TITLE
Tray publisher: Simple families from settings

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Brief description
Added simplified version of TrayPublisher publishing.

## Description
It is possible to "add" creators into TrayPublisher using settings. These creators must define family, allowed extensions and if supports sequences and optionally can enter identifier, icon, label, descritption and if "review" family should be added. Single "creation" allows only one file item: "single file" or "single sequence of files" AKA frame sequence. Removed workfile creator and added `workfile` family to default settings. Previous 'workfile' publishing plugins were generalized. Few publisher UI enhancements/fixes.

## Additional info
Implemeneted default `TrayPublishCreator ` which has implemented all basic methods related to tray publisher and `SettingsCreator` used for simple variant of tray publisher. Slightly modified handling of `FileDef` and it's UI. Result of `FileDef` is `FileDefItem` which can be converted to and from dictionary. Holds more information about files in it, for example if represents sequence and which frames of sequence so creator can know that user added files as sequence or as single files if needed.

FileDef UI does not show text input but always shows view. View not allow to drop files with unsupported extensions. Sequences can be split into multiple files (cannot be joined back). Delete button is not on each item but at bottom of view.

## TODO / Known issues
- ~~Multiselection of FileDef UI is not handled~~
- FileDef UI does not show allowed extensions (not 100% sure where to put it?)
- Remove button can be over items
- Add more generic creators

## Testing notes:
**Try workfile publishing**
**Add new creator**
1. Add new creator in `project_settings/traypublisher/simple_creators`
- for example `"image"` family with `".png"` and `".jpg"` extension that allows sequences
2. Try publish something using new creator

### CODE REVIEW

**Comment by kalisp** [comment]
`filepath` produces weird result for workfiles with spaces:
Screenshot 2022-04-27 125617

**Comment by mkolar** [comment]
> `filepath` produces weird result for workfiles with spaces)

spaces......ouch.

**Comment by iLLiCiTiT** [comment]
That's just has `pprint` resolves too long strings but it is ok.

**Review by mkolar — CHANGES_REQUESTED** [review]
`enable review` checkbox has no effect, I'm assuming it's because we don't have plugins that would support the data it adds.

Secondly these two don't show up anywhere. 
image

**Comment by mkolar** [comment]
resolves #3054

**Comment by iLLiCiTiT** [comment]
> enable review checkbox has no effect, I'm assuming it's because we don't have plugins that would support the data it adds.

Added `traypublisher` to ExtractReview and ExtractBurnin plugins.

> Secondly these two don't show up anywhere.

Fixed

**Pull request merged**
