### PR TITLE
Hiero: Fix inventory check on launch

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Brief description
Hiero inventory check is working again by using right kwarg in function.

## Description
~Fixed kwargs `repre_ids` -> `representation_ids` in `get_representations`.~ Refactored `check_inventory_versions` to use `filter_containers` from load utils which reduced the code and fixed the source issue.

## Testing notes:
1. Load "not last version" to hiero workfile
2. Reopen hiero
3. Scene inventory should show

### CODE REVIEW

**Comment by BigRoy** [comment]
Actually [this looks like a bug](https://github.com/pypeclub/OpenPype/blob/c35dde88ee2ce3e5522010fd44838722d7bbd2c8/openpype/hosts/hiero/api/lib.py#L1069-L1077)? `for track_item in track_item`? and `track_item = track_items or get_track_items()`.

I suspect that should be:
```python
    track_items = track_items or get_track_items()
    # presets
    clip_color_last = "green"
    clip_color = "red"

    item_with_repre_id = []
    repre_ids = set()
    # Find all containers and collect it's node and representation ids
    for track_item in track_items:
        container = parse_container(track_item)
        if container:
            repre_id = container["representation"]
            repre_ids.add(repre_id)
            item_with_repre_id.append((track_item, repre_id))
```
Note the extra **s** on `track_items`

**Comment by iLLiCiTiT** [comment]
From single line fix to Hiero refactor :D

**Comment by BigRoy** [comment]
Haha, just wondering. The second comment I mentioned does seem like a typo/bug though.

**Comment by iLLiCiTiT** [comment]
The suggestion looked good so I did the change.

**Comment by jakubjezek001** [comment]
> Note the extra **s** on `track_items`

Yes, that didn't look right - wonder could we blame for such a code!

**Review by jakubjezek001 — APPROVED** [review]
works well

**Pull request merged**
