### PR TITLE
Maya: Stop creation of reviews for Cryptomattes

### PR DESCRIPTION
**Pull request by antirotor**
## Quick fix

This is fixing an issue where cryptomattes were still used for generation review videos even if they shouldn't. This then caused crash with ffmpeg during publishing because it cannot handle data stored in exrs.

---

### How to test

Publish render from Maya with cryptomattes enabled in any AOV.

🗒️ This is really just quick fix and proper solution is needed. Currently we are looking for `crypto` string in subset name but this is too broad definition.

### CODE REVIEW

**Comment by iLLiCiTiT** [comment]
Why it is crashing? Shouldn't this be fixed with https://github.com/pypeclub/OpenPype/pull/2635/files ?

**Comment by antirotor** [comment]
> Why it is crashing? Shouldn't this be fixed with https://github.com/pypeclub/OpenPype/pull/2635/files ?

ffmpeg is not handling CryptoMesh channel for some reason

```
2-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh.A.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh.B.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh.G.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh.R.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh00.A.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh00.B.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh00.G.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh00.R.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh01.A.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh01.B.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh01.G.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh01.R.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh02.A.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh02.B.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh02.G.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh02.R.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh03.A.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh03.B.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh03.G.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh03.R.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh04.A.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh04.B.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh04.G.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh04.R.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh05.A.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh05.B.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh05.G.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Unsupported channel CryptoMesh05.R.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Missing red channel.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Missing green channel.
2022-03-01 16:12:16:  0: STDOUT: [exr @ 000001cc04432440] Missing blue channel.
2022-03-01 16:12:16:  0: STDOUT: [exr_pipe @ 000001cc04430500] decoding for stream 0 failed
2022-03-01 16:12:16:  0: STDOUT: [exr_pipe @ 000001cc04430500] Could not find codec parameters for stream 0 (Video: exr, none): unspecified size
2022-03-01 16:12:16:  0: STDOUT: Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
```

**Comment by iLLiCiTiT** [comment]
> ffmpeg is not handling CryptoMesh channel for some reason

So it is not converted using oiio or it is converted wrong. Because it does work in ExtractReview, or?

**Comment by antirotor** [comment]
> > ffmpeg is not handling CryptoMesh channel for some reason
> 
> So it is not converted using oiio or it is converted wrong. Because it does work in ExtractReview, or?

This is in `ExtractJpegEXR` plugin, no oiio involved. I think this plugin should actually be reworked to use oiio rather then ffmpeg. Let ffmpeg handle video data and oiio sequences.

**Review by iLLiCiTiT — APPROVED** [review]

**Pull request merged**
