### PR TITLE
OpenPypeV3: add key task type, task shortname and user to path templating construction

### PR DESCRIPTION
**Pull request by ClementHector**
following: [old PR](https://github.com/pypeclub/OpenPype/pull/2119)

### CODE REVIEW

**Comment by mkolar** [comment]
We're doing some last test with standalone publishing with this and will be happy to merge afterwards. @iLLiCiTiT please push on those tests with @64qam

**Comment by iLLiCiTiT** [comment]
I would approve it when this is merged https://github.com/Ellipsanime/OpenPype/pull/2

**Review by iLLiCiTiT — APPROVED** [review]

**Comment by ClementHector** [comment]
@mkolar  Do you think it ready to merge?

**Comment by mkolar** [comment]
It is indeed. Sorry it took a while, it's quite large though so we needed to make sure.

**Comment by ClementHector** [comment]
No problem, it's normal, thank you!

**Pull request merged**
