### PR TITLE
Photoshop: Fix subset name match creator if use selection

### PR DESCRIPTION
**Pull request by ClementHector**
Photoshop Creator Behavior:

- if `use selection`:
  - if you create a subset group for the whole selection, the subset takes the name of the interface.
    image
    image
  - if several objects are selected, the subset takes the name of the interface + the group
   image
   image
- if not `use selection`, create an empty group subset in top level with the name of the interface subset 
 image

### CODE REVIEW

**Review by mkolar — APPROVED** [review]
conceptually this looks solid to me. @kalisp if you could please check the code and functionality please

**Comment by kalisp** [comment]
What is purpose of empty group created when `useSelection` is set to False? That is breaking current implementation. 
Currently if `useSelection` is set to False, all layers/groups (doesn't matter if selected or not) are grouped into new group, essentially "flattening" all layers into final single image.
In this implementation artist would need to move everything under empty group manually. One could argue, that same behavior could be achieved by selecting all layers/groups, `useSelection` to True and not creating single image per layer, but why have empty group?
Could you please elaborate your use case?

**Review by kalisp — CHANGES_REQUESTED** [review]
What is purpose of empty group created when useSelection is set to False? That is breaking current implementation.
Currently if useSelection is set to False, all layers/groups (doesn't matter if selected or not) are grouped into new group, essentially "flattening" all layers into final single image.
In this implementation artist would need to move everything under empty group manually. One could argue, that same behavior could be achieved by selecting all layers/groups, useSelection to True and not creating single image per layer, but why have empty group?
Could you please elaborate your use case?

**Comment by ClementHector** [comment]
> What is purpose of empty group created when useSelection is set to False? That is breaking current implementation. Currently if useSelection is set to False, all layers/groups (doesn't matter if selected or not) are grouped into new group, essentially "flattening" all layers into final single image. In this implementation artist would need to move everything under empty group manually. One could argue, that same behavior could be achieved by selecting all layers/groups, useSelection to True and not creating single image per layer, but why have empty group? Could you please elaborate your use case?

The creation of the empty group comes from several points:
  - the coherence between the DCC, some artists use maya and photoshop, they were disturbed by a different functioning.
  - to create an empty folder, you have to do "use selection" and select nothing, it doesn't seem obvious.

In our workflow, artists have an indefinite number of sketches to produce for an asset. He creates the "subset folder" and builds their sketch in it, then repeats the operation as many times as necessary.
I can go back on this point and educate our artists to create the subset with an empty selection, but beyond that I would like to have the same behavior in all the DCCs, I could make the standardization in the software that we are using.

**Review by kalisp — APPROVED** [review]

**Pull request merged**
