### PR TITLE
Global: add global validators to settings

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changes
- `ValidateInstanceInContext` split into maya and nuke plugin
    - added settings for each of them
- context anatomy collector also stores task type of  context
- start/stop timer plugins are using settings stored in context instead of loading them again
- `ValidateIntent` is for all hosts by default and added profiles to filter validations (by default is plugin disabled)
- `ValidateVersion` added `active` attribute to be able define if is activated by default

## QUESTIONS
- `ValidateContainers` - currently has settings in each host settings and not sure if should be added to global publish plugins settings and if yes than it will probably need profiles but at the same time should have `optional` (maybe) does it make sense to have both `optional` + `active` and `profiles` under that?
- ~~`ValidateResources` I actually don't know why are resources validated?~~ is required does not need settings

### CODE REVIEW

**Comment by mkolar** [comment]
Task linked: [PYPE-1332 Add Global validators to settings](https://app.clickup.com/t/6658547/PYPE-1332)

**Review by jakubjezek001 — CHANGES_REQUESTED** [review]
missing ValidateVersion active attribute in setting schema

**Comment by iLLiCiTiT** [comment]
> missing ValidateVersion active attribute in setting schema

Fixed

**Review by jakubjezek001 — APPROVED** [review]
works fintastic ;)

**Pull request merged**
