### PR TITLE
Invitee email can be None which break the Ftrack commit.

### PR DESCRIPTION
**Pull request by tokejepsen**

### CODE REVIEW

**Review by iLLiCiTiT — APPROVED** [review]
Approving

**Comment by jezscha** [comment]
> Approving

awesome! Do we need to convert this to v3? @iLLiCiTiT

**Comment by jezscha** [comment]
@tokejepsen please follow the name convention for branches. `bugfix` is targeting `2.x/develop` and `hotfix` goes to `2.x/main`

**Comment by iLLiCiTiT** [comment]
> Do we need to convert this to v3?

v3 PR https://github.com/pypeclub/OpenPype/pull/1788

**Comment by tokejepsen** [comment]
> @tokejepsen please follow the name convention for branches. `bugfix` is targeting `2.x/develop` and `hotfix` goes to `2.x/main`

Sorry, yeah will do from now.

**Pull request merged**
