### PR TITLE
Maya capture 'isolate_view' fix + minor corrections

### PR DESCRIPTION
**Pull request by 2-REC**
Maya capture 'isolate_view' preset was ignored.
(related to closed issues #367 and #425)

### CODE REVIEW

**Comment by iLLiCiTiT** [comment]
> Updated Qt.py

Qt.py is module in openpype venv so all you need is to use `from Qt import ...` . Please remove Qt.py from vendor it's on 3 places right now.

**Comment by 2-REC** [comment]
@iLLiCiTiT 
I see the problem with a different Qt.py, but it is part of the 'capture_gui' lib/module.
We would need to modify the 'capture_gui' code everywhere it uses Qt.py.

Shouldn't this "vendor module" be independent of Pype, and include its own dependencies?
It is definitely not ideal to have several Qt.py in the project, but does it have an impact on the rest of the project/code?
(The module/file location doesn't seem to be in sys.path, so it should'nt be conflicting)


Do you suggest to adapt the 'capture_gui' code to NOT use its 'vendor' Qt.py, and to rely on Pype's version?

**Comment by mkolar** [comment]
Actually we're not using capture_gui anywhere in the code at all anymore. so we should really remove it completely :D

never noticed, that it stayed behind as legacy

**Comment by 2-REC** [comment]
@mkolar 
I saw that in Pype3 the use of 'capture_gui' had been completely removed.
However in pype2 there is still a possible case where it is used: when calling 'load_capture_preset' with empty presets (None or {}), the function 'capture_gui.lib.load_json(path)' is called (resulting also in an error, as 'path' is also None).
It is probably from an older feature that has been removed.

So as you say, it should probably be removed now (even in pype2).
I can removed it and update my branch if you want.

**Review by mkolar — APPROVED** [review]
Yes I'm happy with removing capture_gui. the rest is ok. thank you

**Pull request merged**
