### PR TITLE
Bugfix/op 2472 maya assembly collection broken

### PR DESCRIPTION
**Pull request by Allan-I**
Assembly collection fix for issue #2573 

Passing matrix transforms to the instance.data by recognizing the children of the root transform as well and grabbing the transforms of the children to be passed.

### CODE REVIEW

**Comment by Allan-I** [comment]
My initial thinking is that we need to pass children of the root nodes to the hierarchy as well as the `matrix_data` through `get_container_members ` but I'm not entirely sure of the step afterwards, since `matrix_data` is getting its matrix through `get_matrix_data`, so storing the children would require putting them in a dictionary, maybe?

**Comment by mkolar** [comment]
There are actually more problems with this it turns out. 

1. we've accidentally broken the collection also in an unrelated plugins (openpype\plugins\publish\collect_resources_path.py) by relying on `hierarchy` inside instance.data. Unfortunately that is a global plugin and in editorial it holds something else thatn in assembly. So firstly that key should be renamed in the assembly collector to something else. 

Nevertheless, due to other changes in how we construct namespaces of loaded subsets I have a feeling that we broken the assembly publisher in general, because even after I bypass the hierarchy problem. The alembic groups that are published don't match the .json so it cannot be loaded into a scene correctly anyways. That's because we strip namespaces during the extraction I suppose. 

I'm wondering considering this was discovered only recently, it mean this is not being used in production at all, and might be actually worth finally doing it properly with USD structure. that we were discussing internally for a while and @antirotor is working on a rudimentary resolver, that would solve a lot of these issues. @BigRoy are you guys using assemblies at all. The idea was good, but we found the implementation was never quite enough for production.

**Comment by BigRoy** [comment]
> are you guys using assemblies at all.

No. Kill it with fire 🔥 if you can!

**Comment by mkolar** [comment]
Agreed across the board. We'll soon open up wide conversation about USD implementation instead.

**Pull request closed without merging**
