### PR TITLE
Feature Maya import asset from scene inventory

### PR DESCRIPTION
**Pull request by kalisp**
Closes PYPE-1399

Screenshot 2021-09-14 155903

### CODE REVIEW

**Review by mkolar — CHANGES_REQUESTED** [review]
This does the job, however I think we need to remove the container from the scene as well considering from the point of import, we can't do anything with it anyway. It is a bit confusing that it's still listed and appears as actionable.

**Comment by davidlatwe** [comment]
+1 for removing the container.

Not sure the end goal of this feature is the same as what my studio have, so just my 2 cents :
For look type subset, maybe copy and re-path those published texture files into workspace is also desired ?

**Comment by mkolar** [comment]
>Not sure the end goal of this feature is the same as what my studio have, so just my 2 cents :

This was a simple request, to just be able to import references in the scene, but indeed it is directly related to your feature. You just got it further. I like your approach so let's maybe have a look if we can port it to us as and upgrade to this!

**Review by antirotor — APPROVED** [review]
works for me

**Review by mkolar — APPROVED** [review]
don't know what was happening before, but good for mee as well

**Pull request merged**
