### PR TITLE
Deadline Maya rendering pyblish plugin "override output" option

### PR DESCRIPTION
**Pull request by jlorrain**
Add an "override output" option to the maya render selection set

### Why
Allow the operator to override the project rendering output path to perform rendering tests.

### How
You can now specify an output path within the Override Output field in the extra attributes of the maya rendering selection set
image

This Path will be used to set the "OutputFilePath" and the "OutputDirectory" submission parameters of the deadline Plugin and Job

### CODE REVIEW

**Review by antirotor — CHANGES_REQUESTED** [review]
Other than the path check it is working great and I'll be happy to merge it.

**Comment by BigRoy** [comment]
This should be cross checked with #2390 and #2679 regarding safety of cleanup.

**Comment by mkolar** [comment]
@antirotor could you give this one more look please? Not sure if we can do anything about it on our end. @jlorrain are you guys using this in production right now?

**Comment by ClementHector** [comment]
@mkolar This is no longer used at ellipsanime, and @jlorrain has gone on to another adventure ;) I think you can close it.

**Comment by mkolar** [comment]
I agree we should close this as its a bit too dangerous and there doesn't seem to be any real demand for this among current users.

**Pull request closed without merging**
