### PR TITLE
Maya look data contents fails with custom attribute on group

### PR DESCRIPTION
**Pull request by moonyuet**
## Brief description
Solving the failure of validating look data contents when custom attributes are set up on group

## Solution
Set up the condition to tell the relative validating scripts to exclude the nodes with custom attributes from the invalid list, when the system is checking if the attributes are on nodes with IDs.

### CODE REVIEW

**Comment by BigRoy** [comment]
This seems like an odd fix. 

Shouldn't all entries in `lookdata["attributes"]` have attribute changes in `attr_changes["attributes"]` to begin with?

**Comment by moonyuet** [comment]
Hi Roy, I have checked the function of collect_attributes_changed from _collect_look.py_ particularly for this issue. I saw this below:
`            attributes.append({"name": node,
                               "uuid": lib.get_id(node),
                               "attributes": node_attributes})
`
If I understand correctly, the for-loop condition in _validate_look_data_contents.py_ shows that `attr_changes["name"]`, `attr_changes["uuid"]` and `attr_changes["attributes"]` are the elements iterating through `lookdata["attributes"]`.

**Comment by BigRoy** [comment]
Ah yes, the root of the issue does appear to be there! I originally assumed cases without actual values would be ignored as [this code tries to do](https://github.com/pypeclub/OpenPype/blob/develop/openpype/hosts/maya/plugins/publish/collect_look.py#L542-L544). However, the [code just below skips some additional cases of attributes](https://github.com/pypeclub/OpenPype/blob/develop/openpype/hosts/maya/plugins/publish/collect_look.py#L546-L553) with the `continue` statement.

As such, it's probably better to also exclude that node completely when `not node_attributes`.

It might thus make most sense to change the collecting to ignore the cases correctly [around line 554](https://github.com/pypeclub/OpenPype/blob/develop/openpype/hosts/maya/plugins/publish/collect_look.py#L554):
```python
            # Only include if there are any properties we care about
            if not node_attributes:
                continue
```

What do you think?

**Comment by moonyuet** [comment]
I agree. I think it'd be logically concise to implement your suggested conditions to entirely exclude the node when it isn't with `node_attributes`. 
Will add your suggested code later in `collect_look.py`

**Comment by m-u-r-p-h-y** [comment]
linking with issue #3534

**Review by m-u-r-p-h-y — APPROVED** [review]
now it passes the validation with custom attributes on the group

image


so the issue is resolved, but not sure if all doubts were resolved as well . .

**Pull request merged**
