### PR TITLE
Feature/sync server priority

### PR DESCRIPTION
**Pull request by kalisp**
Implemented priority in Summary View, Detail view, sorting when quering for synchronization.

Single edit on double click or context menu.
Multi edit on context menu only.

### CODE REVIEW

**Comment by kalisp** [comment]
Implemented comments:

> Editable action (Reset active or remote site, Set priority) only available if active or remote site is set to local 
> Priority could be set only on local site
> Pausing in Queue GUI pauses only synchronization, not GUI (bug)

**Review by mkolar — CHANGES_REQUESTED** [review]
Limiting priority to only local site works, albeit only when it is set as active. If `local` site is set to remote, it's not possible to change the priority, or rather it appears in GUI as if it was possible to change the priority, but the change doesn't take effect.

When no local site is present in Active or Remote, I can also see the edit icon when hovering, but this time can't get to the edit mode at all. We should remove the icon displaying on hover, so we don't confuse the user. 

After clicking on priority in representation detail, the edit mode stays active. I reckon it should go back to the original value if the user did it accidentally, and didn't fill anything in there. 

image

**Comment by kalisp** [comment]
Fixed mentioned issues.
Reworked when querying is happening.

**Review by mkolar — APPROVED** [review]

**Comment by mkolar** [comment]
Looking good

**Pull request merged**
