### PR TITLE
Maya : V-Ray Proxy - load all ABC files via proxy

### PR DESCRIPTION
**Pull request by karimmozilla**
## Description
Add option to load alembic files published using `model` family with V-ray proxy loader.

## Testing notes:
1. load alembic model from OP loader with `Import VRay Proxy (abc)`.

### CODE REVIEW

**Comment by mkolar** [comment]
Task linked: [OP-2007 V-Ray Proxy - load all ABC files via proxy](https://app.clickup.com/t/6658547/OP-2007)

**Comment by BigRoy** [comment]
Why is GitHub also showing Avalon core changes and vendorized studio library? That seems odd?

The change to the V-Ray loader looks perfect. Haven't tested this code but we had done something similar with our V-Ray proxies loader outside of OpenPype and that worked out solid.

**Comment by antirotor** [comment]
> Why is GitHub also showing Avalon core changes and vendorized studio library? That seems odd?

It's doing this because updated avalon-core git submodule and added studio library submodule. I suggest to take them out of this PR as they are not related to keep it clean.

**Review by antirotor — DISMISSED** [review]
It works perfectly. I would just remove avalon-core update and studio library sub module from this PR

**Review by mkolar — APPROVED** [review]

**Pull request merged**
