### PR TITLE
General: Validate third party before build

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Brief description
Goal is to validate 3rd party binaries before build starts.

## Description
Added validation of ffmpeg nad oiio to `setup.py`.

### CODE REVIEW

**Comment by mkolar** [comment]
Task linked: [OP-2065 Validate third party before build](https://app.clickup.com/t/6658547/OP-2065)

**Comment by kalisp** [comment]
Could we yank this out into a lib, I think there is something similar in `start.py`? (Not sure if this doesn't replace that one.)

**Comment by iLLiCiTiT** [comment]
> I think there is something similar in start.py?

It was copied from `start.py` and it must stay there because you can run openpype without building (from code).

> Could we yank this out into a lib

Well where would you put it? Because setup.py should not touch anything in igniter or openpype and start.py is converted into binary file and the lib file would add new dependency python file.

**Comment by antirotor** [comment]
It does work, for me and it is doing its job. But there is one issue for CI - until now, we never fetched ffmpeg/oiio before the build check and we need to do it now. Ideas @mkolar ? Downloading it each time doesn't seem to be smartest thing to do. Add switch to disabled the check?

**Comment by mkolar** [comment]
>Ideas @mkolar ? Downloading it each time doesn't seem to be smartest thing to do. Add switch to disabled the check?

yeah for pure build tests, it's a problem of course. Useless traffic really. Switch would be the best option probably, so we can skip it for PR tests. but have it run once we finish build and binary upload

**Comment by iLLiCiTiT** [comment]
Validation is skipped if environment variable `SKIP_THIRD_PARTY_VALIDATION` is set.

**Review by mkolar — APPROVED** [review]

**Pull request merged**
