### PR TITLE
Settings UI use OpenPype styles

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Goal
Setting UI should use OpenPype styles instead of having it's own.

## Changes
- local settings and studio settings use openpype's stylesheet
- most of settings stylesheet copied to openpype stylesheet
    - not all are same
- most of buttons in settings have real image instead of using characters
     - their size is based on font size
- use new checkbox which has size defined by font size
    - few fixes in new checkbox

## Note
If anything is so different that is' bad tell me in comments.

### CODE REVIEW

**Comment by mkolar** [comment]
Task linked: [OP-1775 Settings UI use openpype styles](https://app.clickup.com/t/6658547/OP-1775)

**Comment by mkolar** [comment]
I made a small comparison screen and have some comments

**Review by mkolar — CHANGES_REQUESTED** [review]
Changes in comment above

**Comment by iLLiCiTiT** [comment]
Modified icon images
image

**Comment by iLLiCiTiT** [comment]
Modified colors of checkbox
image

**Comment by iLLiCiTiT** [comment]
Current state. Left: Previous - Right: this PR
image

**Review by jakubjezek001 — APPROVED** [review]
looks as it is shown in your last screenshot (beautiful - if you asked me ;)

**Review by 64qam — APPROVED** [review]

**Review by mkolar — APPROVED** [review]

**Pull request merged**
