### PR TITLE
Unreal: Use client query functions

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Brief description
Modified Unreal host to use query functions from [PR](https://github.com/pypeclub/OpenPype/pull/3288).

## Description
Unreal is using query functions from `openpype.client` to get versions.

## Testing notes:
1. Load Camera - try load camera
2. Load Layout - try load layout
3. Extract layout should work

### CODE REVIEW

**Comment by simonebarbieri** [comment]
I'm getting this error for both camera and layout loading:
```
Traceback (most recent call last):
  File "C:\Dev\OpenPype\openpype\openpype\tools\loader\widgets.py", line 1556, in _load_representations_by_loader
    options=options
  File "C:\Dev\OpenPype\openpype\openpype\pipeline\load\utils.py", line 285, in load_with_repre_context
    return loader.load(repre_context, name, namespace, options)
  File "C:\Dev\OpenPype\openpype\openpype\hosts\unreal\plugins\load\load_layout.py", line 631, in load
    sequence, frame_range = self._generate_sequence(h, h_dir)
  File "C:\Dev\OpenPype\openpype\openpype\hosts\unreal\plugins\load\load_layout.py", line 371, in _generate_sequence
    fields=["_id", "data.clipIn", "data.clipOut"]
TypeError: get_assets() got an unexpected keyword argument 'parent_ids'
```

**Review by simonebarbieri — CHANGES_REQUESTED** [review]
I'm getting this error for both camera and layout loading:
```
Traceback (most recent call last):
  File "C:\Dev\OpenPype\openpype\openpype\tools\loader\widgets.py", line 1556, in _load_representations_by_loader
    options=options
  File "C:\Dev\OpenPype\openpype\openpype\pipeline\load\utils.py", line 285, in load_with_repre_context
    return loader.load(repre_context, name, namespace, options)
  File "C:\Dev\OpenPype\openpype\openpype\hosts\unreal\plugins\load\load_layout.py", line 631, in load
    sequence, frame_range = self._generate_sequence(h, h_dir)
  File "C:\Dev\OpenPype\openpype\openpype\hosts\unreal\plugins\load\load_layout.py", line 371, in _generate_sequence
    fields=["_id", "data.clipIn", "data.clipOut"]
TypeError: get_assets() got an unexpected keyword argument 'parent_ids'
```

**Comment by iLLiCiTiT** [comment]
That's because I forgot to commit.

**Review by simonebarbieri — APPROVED** [review]
It works now 👍

**Pull request merged**
