### PR TITLE
Nuke: Compatibility with Nuke 13

### PR DESCRIPTION
**Pull request by jakubjezek001**
# Description
Nuke had changed version of python interpreter to 3.7. There were couple issues which had been blocking Nuke 13 from runing and publishing.

# Dependencies
avalon-core: https://github.com/pypeclub/avalon-core/pull/367

# Testing notes
- we need to test launching Nuke13
- Loading should work but somehow it feels like the Loader is taking some time to start
- Manager is opening too but also it feels like ages before it opens
- Publishing works and render local, publish rendered frames and render on farm was working
- Since the nuke app label had changed Settings has to be resaved

### CODE REVIEW

**Comment by jakubjezek001** [comment]
Task linked: [PYPE-1823 Nuke 13 compatibility](https://app.clickup.com/t/6658547/PYPE-1823)

**Comment by jrsndl** [comment]
I tested Nuke 13 and it seems to work fine.

- Loading Nuke 12.2 project OK
- Publishing locally OK
- Publishing with existing frames OK
- Publishing with prerender OK
- Set Frame Range OK
- Set Resolution OK
- Set Colorspace OK
- Apply All Settings OK
- Loader works, delay before opening bit more than 1sec on Ryzen 5900X (same as Nuke 12)
- Manager works, delay before opening bit more than 1sec on Ryzen 5900X (same as Nuke 12)

I am not able to test farm publish

**Review by jrsndl — COMMENTED** [review]
I tested Nuke 13 and it seems to work fine.

- Loading Nuke 12.2 project OK
- Publishing locally OK
- Publishing with existing frames OK
- Publishing with prerender OK
- Set Frame Range OK
- Set Resolution OK
- Set Colorspace OK
- Apply All Settings OK
- Loader works, delay before opening bit more than 1sec on Ryzen 5900X (same as Nuke 12)
- Manager works, delay before opening bit more than 1sec on Ryzen 5900X (same as Nuke 12)

I am not able to test farm publish

**Review by jrsndl — APPROVED** [review]

**Comment by 64qam** [comment]
Looks good, as Jirka mentioned the Manager and Loader windows delay is about 1-2 second.

**Review by 64qam — APPROVED** [review]

**Pull request merged**
