### PR TITLE
Deadline: Simplify GlobalJobPreLoad logic

### PR DESCRIPTION
**Pull request by BigRoy**
## Brief description

This simplifies the logic the Deadline plug-in requires to retrieve the OpenPype Executable.

- No need to re-save/update the Job to inject OpenPype Executable - the setting is now loaded live from the OpenPype plug-in.
- The OpenPype Event Plug-in was only used for injecting the OpenPype Executable info into the job - since that's redundant now, that has been removed. That also means you now only have to set the executable in the regular Deadline OpenPype plug-in (not the Event plug-in).
- I've removed the 'invalidate cache' code of getting the Job since now the Job doesn't need to be altered/re-saved we don't need to really invalidate any caches anyway.

---

Would love to hear whether this would move it in a good direction or whether this is not preferred?

The Event Plug-in also had some "ftrack" related functions which was basically doing nothing currently. I'm not sure if there might be customers out there how do have that logic altered instead and thus the Event Plug-in might still have a place. Something to consider at least.

### CODE REVIEW

**Comment by kalisp** [comment]
I am all up for removing the event, I really hated it anyway.

**Review by kalisp — CHANGES_REQUESTED** [review]
Could you also please purge all mentions of DL event in `vendor/readme.md` and `website/docs/module_deadline.md`?

**Comment by BigRoy** [comment]
> Could you also please purge all mentions of DL event in vendor/readme.md and website/docs/module_deadline.md?

Sure can! Like [this](https://github.com/pypeclub/OpenPype/pull/2605/commits/dba50e9fb0fb2783eef1354ecc24acc500810bd9)?

**Comment by BigRoy** [comment]
Any chance we can get the Build/Docs deployment to run again @kalisp @mkolar ?

---

> It seems doc building is failing on GitHub:

```
Run cd website
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
error @docusaurus/core@2.0.0-beta.15: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.10"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

> Seems we will need to update node to 14.x?
> Here: > https://github.com/pypeclub/OpenPype/blob/3bc8ae4e3b34cd980db9aad8b47b9437cfd78e3b/.github/workflows/documentation.yml#L23
> And on line 44.
> I believe that'd be updating Node.js
> 
> Not sure if that'd break anything else however.

(Copied from Discord)

**Review by kalisp — APPROVED** [review]
Looks great. 

I will keep it unmerged for now to not hide issue with documentation build. After that I would merge it.

**Comment by BigRoy** [comment]
With https://github.com/pypeclub/OpenPype/pull/2760 merged should these doc builds now pass @mkolar ?

It appears to still fail.

**Comment by mkolar** [comment]
It should indeed work now, but you need to merge develop to this branch. Github actions are picked from currently checked out branch.

**Comment by BigRoy** [comment]
> It should indeed work now, but you need to merge develop to this branch. Github actions are picked from currently checked out branch.

@mkolar  Now the check suddenly is gone and thus no documentation build is checked?

**Pull request merged**
