### PR TITLE
Update submodules.

### PR DESCRIPTION
**Pull request by icyvapor**
## Brief description
Update submodules.

## Description
Did this mostly to get to Roy's changes for Houdini19 support in `avalon-core`.  Could you guys review that whether OP is ready for the latest of these submodules?

### CODE REVIEW

**Comment by iLLiCiTiT** [comment]
We can't update arrow and ftrack-api those are last versions supporting python 2.

**Comment by mkolar** [comment]
But we could potentially vendorize the old ftrack API for py2 hosts, and switch to the latest for the rest, couldn't we?

**Comment by icyvapor** [comment]
Doh what have I got myself into.. 

So could we just bump up 'avalon-core' by itself?

**Comment by mkolar** [comment]
>So could we just bump up 'avalon-core' by itself?

that we could indeed. We tend to do it with releases.

**Comment by mkolar** [comment]
Avalon-core was updated in the latest develop.

**Comment by mkolar** [comment]
I will close this PR, because it needs a bit more though, to prevent any ugly breakage. @icyvapor do you need the ftrack API and arrow updates for something specific?

**Comment by icyvapor** [comment]
> I will close this PR, because it needs a bit more though, to prevent any ugly breakage. @icyvapor do you need the ftrack API and arrow updates for something specific?

Nope all good, thank you!!

**Pull request closed without merging**
