### PR TITLE
Maya: Include task name in render pass subset naming

### PR DESCRIPTION
**Pull request by tokejepsen**
## Brief description
Include task name in render pass subset naming

## Description
We include task name to avoid cross task overwriting.

## Testing notes:
1. Create a render in Maya with render pass.
2. Render and check subset name includes task name.

### CODE REVIEW

**Comment by antirotor** [comment]
Maybe we should add this to project settings so it can be changed per project? The default will be the current way so it won't break any existing productions but you can change it as needed on new projects...

**Comment by iLLiCiTiT** [comment]
Isn't the task name inside the subset name by default (so it's double information)?

**Comment by tokejepsen** [comment]
> Isn't the task name inside the subset name by default (so it's double information)?

The passes are hardcoded to not include it; https://github.com/pypeclub/OpenPype/blob/develop/openpype/hosts/maya/plugins/publish/collect_render_layer_aovs.py#L65

**Comment by iLLiCiTiT** [comment]
> The passes are hardcoded to not include it;

But it's using `"subset"` which may already have task name in it.

**Comment by tokejepsen** [comment]
@LiborBatek did you end up testing whether the task name was included in the render pass subset naming before this PR?

**Comment by LiborBatek** [comment]
@tokejepsen if I am not mistaken yes the second screenshot is showing assets/renders before this PR. Or should I test it some other way? Let me know...

**Comment by tokejepsen** [comment]
@LiborBatek great! Thanks for testing.

**Comment by iLLiCiTiT** [comment]
The plugin is running only `if not instance.data("extendFrames", False):` how that can happen?

**Comment by tokejepsen** [comment]
@iLLiCiTiT wrong issue?

**Pull request closed without merging**
