### PR TITLE
Maya: Vray fix proxies look assignment

### LINKED ISSUE #2231: Maya: Vray - handle vrmeshes in look assignment
## Problem

We don't support `vrmesh` type in vray proxy for look assignment as we cannot get object IDs from it. We support only alembics. Nevertheless if artist has `vrmesh` in scene and tries to apply look, it ends up with lot of crashes and confusion. We should at least issue visible warning that he can't assign look to `vrmesh`.

[cuID:1rgq6u8]

### PR DESCRIPTION
**Pull request by antirotor**
## Fix

Fix problems with look assignment and scene with vray proxies. Fixing `Get All Assets` functionality.

There was a bug when there were vray proxies with alembics and vrmeshes combined loaded in scene, that look assigner failed during applying the look. This fix is also restoring functionality of `Get All Assets` button.

### How to test:

Load into scene vray proxy published with OpenPype - that one should be in abc format. Load some vrmeshes manually via vray menu and try to apply look to some of the loaded proxies. Look should be applied correctly. Also - `Get All Assets` button in look assigner should return all loaded assets (list was previously empty due to the bug).

Close #2231

### CODE REVIEW

**Comment by mkolar** [comment]
Task linked: [OP-2016 Maya: Vray - handle vrmeshes in look assignment](https://app.clickup.com/t/6658547/OP-2016)

**Comment by antirotor** [comment]
Added more fixes.

**Review by mkolar — CHANGES_REQUESTED** [review]
When two proxies of the same version are loaded into the scene, Only one of them is ever loaded into look manager, so it's not possible to assign materials to all of them. 

image

**Comment by mkolar** [comment]
Task linked: [OP-2022 Updating Looks fails if vrmesh is in scene](https://app.clickup.com/t/6658547/OP-2022)

**Comment by antirotor** [comment]
It should be fixed now

**Review by iLLiCiTiT — APPROVED** [review]
Code looks ok for me. Don't know how to test functionality.

**Pull request merged**
