### PR TITLE
SFTP provider

### PR DESCRIPTION
**Pull request by kalisp**
Implemented SFTP provider for Site Sync.

Testing SFTP server spun up on AWS, check keeper for 'SFTP test'.

Testing configuration
sftp_settings
sftp_settings_local

### CODE REVIEW

**Comment by mkolar** [comment]
Task linked: [PYPE-1930 Create SFTP provider](https://app.clickup.com/t/6658547/PYPE-1930)

**Review by 64qam — APPROVED** [review]
It works, but the Addons must not be configured. The synchronization will not work (upload will be stalled).

**Comment by mkolar** [comment]
@kalisp can we please resolve the poetry.lock conflict?

**Comment by kalisp** [comment]
Conflict resolved, added some documentation.

**Pull request merged**
