### PR TITLE
AE, PS, TVpaint, Blender: Add option to define path to workfile template

### PR DESCRIPTION
**Pull request by mkolar**
This is a suplemental PR to #1571, which deals with more advanced version currently only for nuke. 

This simply adds option to define a template file and have it used as a first working file on a project and host basis. 

logic is handled in a global pre-hook and might clash with the more complex behaviour of Nuke, but should get us started.

### CODE REVIEW

**Comment by 64qam** [comment]
When setting up a template and trying to launch the application from Launcher, it shows "Permission denied" message, and application will not start.


```
>>> [  Current context does not have any workfile yet.  ]
>>> [  Creating workfile from template: "C:\Users\qam\template"  ]
WARNING:openpype.tools.launcher.window.LauncherWindow:Action launch failed.
Traceback (most recent call last):
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\tools\launcher\window.py", line 441, in run_action
    action().process(filtered_session)
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\tools\launcher\actions.py", line 105, in process
    task_name=task_name
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\lib\applications.py", line 261, in launch
    return self.manager.launch(self.full_name, *args, **kwargs)
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\lib\applications.py", line 364, in launch
    return context.launch()
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\lib\applications.py", line 868, in launch
    prelaunch_hook.execute()
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\hooks\pre_copy_template_workfile.py", line 31, in execute
    from_template = self.workfile_path(last_workfile)
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\hooks\pre_copy_template_workfile.py", line 78, in workfile_path
    os.path.normpath(last_workfile)
  File "C:\Program Files\Python37\lib\shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Python37\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\qam\\template'
```

**Comment by 64qam** [comment]
My bad, I've set only a folder without a file. It would be nice if it checks the correct path with the file.

**Comment by 64qam** [comment]
I am not able to run a workfile template in AE. It always starts in a "factory" template. Other apps are ok.

**Comment by mkolar** [comment]
>I am not able to run a workfile template in AE. It always starts in a "factory" template. Other apps are ok.

thanks I'll check it out

**Comment by mkolar** [comment]
this was merged to #1571 and will be finalised in there

**Pull request closed without merging**
