### PR TITLE
Add IGG logo to index page.

### PR DESCRIPTION
**Pull request by icyvapor**
Add IGG logo to index page.

### CODE REVIEW

**Review by m-u-r-p-h-y — APPROVED** [review]
Perfect. Thank you!

**Comment by icyvapor** [comment]
> Perfect. Thank you!

Nope, thank you guys for setting up this solid pipeline system!

**Review by BigRoy — APPROVED** [review]
❤️

**Comment by mkolar** [comment]
As far as we're throwing hearts around... I want in! 💌💓

**Pull request merged**
