### PR TITLE
Maya: Remove some unused code

### PR DESCRIPTION
**Pull request by BigRoy**
## Brief description

First pass at cleaning up some dead Maya integration code, as a step for #1306 

### Notes

The following functions also appear unused - but I wasn't sure whether to remove them.
```
openpype.hosts.maya.api.lib.without_extension
openpype.hosts.maya.api.lib.remove_id
openpype.hosts.maya.api.lib.unique_name
openpype.hosts.maya.api.lib.no_refresh

```
The `remove_id` might be nice to keep in the API for anyone coding against the OP maya integration. The `without_extension` I wasn't sure about because it was exposed in the `__init__` for the API too. The other ones feel like some that we can remove too?

Also, some of the removed code came from Avalon core and had no use in OP.

### Testing notes

Still needs to be tested in Maya.

### CODE REVIEW

**Comment by BigRoy** [comment]
Did some quick preliminary testing in Maya. Launches fine, seems to work at first sight. I guess it's just a debate about those last potentially unused methods whether it's worth removing those too.

**Review by antirotor — APPROVED** [review]
As these are not used anywhere and it survived my casual playing with Maya I guess it is safe to merge it.

**Comment by tokejepsen** [comment]
Is `openpype.hosts.maya.api.lib.no_refresh` not being used for alembic caching?

**Comment by BigRoy** [comment]
> Is openpype.hosts.maya.api.lib.no_refresh not being used for alembic caching?

No, that is - _how confusing it might seem_ - [`suspended_refresh`](https://github.com/pypeclub/OpenPype/blob/870d3af51907ff44a3442afdb98c2f9dc5c0855f/openpype/hosts/maya/api/lib.py#L119-L127) which differs in code from [`no_refresh`](https://github.com/pypeclub/OpenPype/blob/870d3af51907ff44a3442afdb98c2f9dc5c0855f/openpype/hosts/maya/api/lib.py#L856-L873).

**Comment by antirotor** [comment]
> Any verdict on these still remaining functions that appear unusued?

I would remove them too. Even if they might be useful later, I hate idea to have OP as repository for useful but not used code :) Anyway, we have git history and if needed, they can be resurrected.

**Comment by BigRoy** [comment]
> I would remove them too. Even if they might be useful later, I hate idea to have OP as repository for useful but not used code :) Anyway, we have git history and if needed, they can be resurrected.

Agreed. Removed with https://github.com/pypeclub/OpenPype/pull/2709/commits/b52e511a6e3d233242fa5053434953e4b0a52f8c

Did some preliminary testing in Maya 2020. Still seemed fine, as expected! 👍

**Review by mkolar — APPROVED** [review]

**Comment by tokejepsen** [comment]
Woop woop! -2932 lines!

**Pull request merged**
