### PR TITLE
Maya `vrscene` loader fixes

### PR DESCRIPTION
**Pull request by antirotor**
## Fix

this is fixing obsolete path for imports in `vrsene` loader for Maya.

❗ **To test this, valid vray license is needed**

### CODE REVIEW

**Comment by BigRoy** [comment]
I can test this tomorrow if you'd like?

**Comment by BigRoy** [comment]
I gave this a go.

## Creating a V-Ray Scene Publish

First step was to generate a `vraysceneMain` publish:
```python
import avalon.api
import pyblish.util
import openpype.lib
from maya import cmds

# Ensure V-Ray is loaded
cmds.loadPlugin("vrayformaya", quiet=True)

# Set V-Ray as current renderer
cmds.setAttr("defaultRenderGlobals.currentRenderer", "vray", type="string")

def create(Creator, name, members=None):
    """Create creator for current asset with name + add members"""
    # note: the create method does not "return" the publish instance so for now 
    # we use "useSelection" to add the members - since otherwise it's non trivial.
    options = {"useSelection": True}
    asset = avalon.api.Session["AVALON_ASSET"]
    with avalon.maya.maintained_selection():
        cmds.select(members, replace=True, noExpand=True)
        container = avalon.api.create(Creator, 
                                      name=name, 
                                      asset=asset, 
                                      options=options)
                                      

# Create a polyCube to publish as V-Ray Scene
cube = cmds.polyCube(constructionHistory=False, name="cube_GEO")[0]

# Create instance
Creator = openpype.lib.get_creator_by_name("CreateVRayScene")
create(Creator, name="vraysceneMain")

# Then manually save your scene and publish
# save_scene()
# pyblish.util.publish()
# This will error on Validate V-Ray Translator Settings. You can click Repair to have it set correctly.
```
Repairing the VRay Translator Settings worked pretty good 👍 however I did run into the issue that it wouldn't publish if I wasn't actively inside a Render Setup layer but was currently "viewing" the default render layer.

**Error on VRayScene extraction when currently in the defaultRenderLayer**
```
Traceback (most recent call last):
  File "S:\openpype\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "S:\openpype\OpenPype\openpype\hosts\maya\plugins\publish\extract_vrayscene.py", line 79, in process
  File "S:\openpype\OpenPype\openpype\hosts\maya\api\render_setup_tools.py", line 86, in export_in_rs_layer
    ("Export in Render Setup layer is only supported when in "
AssertionError: Export in Render Setup layer is only supported when in Render Setup layer
```

**Bug in ExtractVrayscene**

I assumed thus it would also always fail if I had two renderlayers but was in one of them, as I couldn't be in both at the same time. But that succeeded - of which I was suspicious. And I think it only really exports the currently active layer instead of the actual render setup layer. It would always export the same current layer even if I had multiple to publish. Checking the published content for that case showed me that actually the non-currently visible layer somehow didn't have the cube in the export?

It retrieves the [current layer](https://github.com/pypeclub/OpenPype/blob/develop/openpype/hosts/maya/plugins/publish/extract_vrayscene.py#L40) for extraction but doesn't "switch to" that layer to run the extraction - which should happen somewhere before [`export_in_rs_layer`](https://github.com/pypeclub/OpenPype/blob/develop/openpype/hosts/maya/plugins/publish/extract_vrayscene.py#L76-L81)

⚠️ So there is still something wrong in that logic. That could be it's own issue/PR and improved separate from this PR - an issue should be created to track the problem however.

---

I also noticed the vrayscene subsets wouldn't prefix with `vrayscene` but would just e.g. become `Main` and `Other` instead of `vraysceneMain` and `vraysceneOther`. Not a problem for me, but just wanted to throw that out here to confirm it's ok.

---

## Loading the V-Ray Scene

The loader however works fine, and can also update versions fine. Did have the following notes:

- I did notice that it's possible to "delete" the node in the outliner. We might want to lock the "shape" node so that you cannot delete it. 
- And also that the extra `_GRP` above the V-Ray Scene transform is a bit redundant because the VRayScene will never exist of multiple nodes, right? So potentially that could be removed.
- The group/root did not get colorized even though the code is there. That's because **vrayscene_layer** was not exposed in the Maya Loader Subset Outliner Colors settings.

Those three points I've tweaked in my fork of your branch [here](https://github.com/BigRoy/OpenPype/tree/bugfix/maya-vrscene-loader-fixes). You should be able to pull those in if you like all of the changes, or otherwise cherry pick the commits you'd like.

**Comment by antirotor** [comment]
I think we can possibly get rid of the render layer dependency as vray scene can now be exported with "export selected"... There still are a few use cases for using render setup but I thing it should be more simple. We also have a request to be able to run model family validators on vrscene. What do you think about it?

**Review by iLLiCiTiT — APPROVED** [review]
Current modifications looks good.

**Comment by BigRoy** [comment]
> Current modifications looks good.

Would that include the modifications in [this branch](https://github.com/BigRoy/OpenPype/tree/bugfix/maya-vrscene-loader-fixes) or just this PR?

**Review by Allan-I — APPROVED** [review]
Looks good to me!

**Comment by antirotor** [comment]
@BigRoy if you added something to your branch, could you please create PR to this one?

**Comment by antirotor** [comment]
> > if you added something to your branch, could you please create PR to this one?
> 
> @antirotor Done with  https://github.com/pypeclub/OpenPype/pull/2698

Thanks, I've missed that

**Comment by antirotor** [comment]
@m-u-r-p-h-y  could you please test it somewhere with vray license? I've merged in @BigRoy modifications and resolved conflicts. Thanks

**Review by m-u-r-p-h-y — APPROVED** [review]
tested, published, submitted to Deadline, render successful  . .

**Pull request merged**
