### PR TITLE
SyncServer: Dropbox Provider

### PR DESCRIPTION
**Pull request by tokejepsen**
**Goal**

To enable syncing files to Dropbox.

**Motivation**

We have moved all our files from Google Drive to Dropbox, and the way we were using Google Drive (using one user for everyone) was not fitting for Sync Server.

**Step To Test**

This was tested with a Dropbox paid account with Team Folders. It should be possible to have Team Folder with free accounts but I have not tested this.

1. Create a Dropbox app: https://developers.dropbox.com/oauth-guide with access to the full Dropbox.
2. Enabled these permissions; `files.content.write`, `files.content.read`, `sharing.read`, `team_data.member`, `team_data.team_space`, `members.read`.
3. Generate the access token and input into the settings.
4. Find your Dropbox user name and input into the settings. If you dont know this, you can leave it blank and an error message will display all available user names.
5. Find your Dropbox team folder name and input into the settings. If you dont know this, you can leave it blank and an error message will display all available team folder names.

**Implementation**

I've copied the GDrive provider but Dropbox is a lot simpler and maybe too naive on this first commit but we can improve on that. Compared with GDrive, Dropbox does not need any tree or folder ids as they are just paths to the files from the Team Folder.

Since the settings for both providers are hardcoded, I have split the settings visually hence why there is a slight change to how GDrive provider gets its settings.

### CODE REVIEW

**Comment by tokejepsen** [comment]
Are the methods `get_system_settings_schema`, `get_project_settings_schema`, `get_local_settings_schema` in effect?

**Comment by kalisp** [comment]
Only `get_system_settings_schema` is, not others.

Unfortunately I am not able to test it on Basic account (`team.*` scope requires Business account). Code looks good otherwise.

Poetry is not updated though, could you please run `poetry add dropbox` and commit changes in `poetry.lock` and `pyproject.toml`?

**Review by kalisp — CHANGES_REQUESTED** [review]
`dropbox` library is missing in poetry definition.

**Comment by tokejepsen** [comment]
> `dropbox` library is missing in poetry definition.

Done

**Review by kalisp — APPROVED** [review]

**Pull request merged**
