### PR TITLE
General: Workfile template build enhancements

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Brief description
Changed implementation of workfile template build system to be plugin based to be able add more build abilities.

## Description
Goal of this PR is to keep exactly the same functionality in nuke and maya but with ability to extend or modify behavior with plugins. The key concepts of previous implementation were kept, there are placeholders in workfile template that can be created and populated. The difference is that only part which define the placeholder logic is plugin. So `PlaceholderItem` is just a data holder and is used to keep progress during population. Placeholder item must have unique scene identifier which is used to identify if placeholder was already processed.

Default process behavior can use nested placeholders. So if one of placeholder items load another template which contain new placeholders, they are processed recursively until all placeholders are processed. 

Changed how options are defined from `qargparse` to attribute definitions. Main reason is requirement of Qt and Qt binding to be able use `qargparse` which is complicated in some cases. Loader is filled with enumerator instead of string. Not sure if it's better, but can be changed back any time.

It is not possible to reuse templates from previous implementation because placeholders in templates don't contain information about plugin.

## Additional notes
I think that this feature deserve full UI tool related to it. Right now it consist of 4 actions without handled exceptions or populate report.

I was able to create only simple Maya template seemed to work but I would like to ask @m-u-r-p-h-y and @LiborBatek to fully validate and report issues.

### Maya template builder
Follow description from [this PR](https://github.com/pypeclub/OpenPype/pull/3578).
- [ ] Maya template build works

### Nuke template builder
Follow description from [this PR](https://github.com/pypeclub/OpenPype/pull/3763).
- [ ] Nuke template build works

### CODE REVIEW

**Comment by kalisp** [comment]
Would this require/benefit some changes in documentation? I found `https://openpype.io/docs/project_settings/settings_project_nuke/#workfile-builder` , not sure if this changes that.

**Comment by iLLiCiTiT** [comment]
We now have 2 workfile builders. Good point is that both have different docs location. These are here https://openpype.io/docs/admin_hosts_maya#templated-build-workfile

**Review by jakubjezek001 — CHANGES_REQUESTED** [review]
==============================
'NukePlaceholderLoadPlugin' object has no attribute 'node_color'
==============================
Traceback (most recent call last):
  File "C:\CODE\__PYPE\OpenPype\openpype\tools\workfile_template_build\window.py", line 222, in _on_create_click
    plugin.create_placeholder(options)
  File "C:\CODE\__PYPE\OpenPype\openpype\hosts\nuke\api\workfile_template_builder.py", line 98, in create_placeholder
    placeholder.knob("tile_color").setValue(self.node_color)
AttributeError: 'NukePlaceholderLoadPlugin' object has no attribute 'node_color'

**Comment by LiborBatek** [comment]
Did test works ok but gives me this warning msg in maya after loading Template scene...not sure how important it is.
```# openpype.lib.profiles_filtering : Looking for matching profile for: task_types: "Modeling" | task_names: "modeling"
# openpype.lib.profiles_filtering : Profile selected: {'task_types': ['Modeling'], 'task_names': [], 'path': 'd:\\PROJECTS\\Libor_Tests\\assets\\props\\atest\\work\\modeling\\220901_atest_modeling_v001.ma'}
# >>> [ Found template at: 'd:\PROJECTS\Libor_Tests\assets\props\atest\work\modeling\220901_atest_modeling_v001.ma' ] 
# Warning: The node '220901_atest_modeling_v001_defaultLayer' still clashed with a node in the main scene.  Renaming to '_atest_modeling_v001_defaultLayer'. # 
# Warning: Edits on '220901_atest_modeling_v001_defaultLayer' may have been lost as a result of renaming. We strongly recommend the use of Namespaces to resolve Name Clashes. # 
# Warning: The node '220901_atest_modeling_v001_defaultRenderLayer' still clashed with a node in the main scene.  Renaming to '_atest_modeling_v001_defaultRenderLayer'. # 
# Warning: Edits on '220901_atest_modeling_v001_defaultRenderLayer' may have been lost as a result of renaming. We strongly recommend the use of Namespaces to resolve Name Clashes. # 
# Warning: The node '220901_atest_modeling_v001_layerManager' still clashed with a node in the main scene.  Renaming to '_atest_modeling_v001_layerManager'. # 
# Warning: Edits on '220901_atest_modeling_v001_layerManager' may have been lost as a result of renaming. We strongly recommend the use of Namespaces to resolve Name Clashes. # 
# Warning: The node '220901_atest_modeling_v001_poseInterpolatorManager' still clashed with a node in the main scene.  Renaming to '_atest_modeling_v001_poseInterpolatorManager'. # 
# Warning: Edits on '220901_atest_modeling_v001_poseInterpolatorManager' may have been lost as a result of renaming. We strongly recommend the use of Namespaces to resolve Name Clashes. # 
# Warning: The node '220901_atest_modeling_v001_renderLayerManager' still clashed with a node in the main scene.  Renaming to '_atest_modeling_v001_renderLayerManager'. # 
# Warning: Edits on '220901_atest_modeling_v001_renderLayerManager' may have been lost as a result of renaming. We strongly recommend the use of Namespaces to resolve Name Clashes. # 
# Warning: The node '220901_atest_modeling_v001_renderSetup' still clashed with a node in the main scene.  Renaming to '_atest_modeling_v001_renderSetup'. # 
# Warning: Edits on '220901_atest_modeling_v001_renderSetup' may have been lost as a result of renaming. We strongly recommend the use of Namespaces to resolve Name Clashes. # 
# Warning: The node '220901_atest_modeling_v001_sceneConfigurationScriptNode' still clashed with a node in the main scene.  Renaming to '_atest_modeling_v001_sceneConfigurationScriptNode'. # 
# Warning: Edits on '220901_atest_modeling_v001_sceneConfigurationScriptNode' may have been lost as a result of renaming. We strongly recommend the use of Namespaces to resolve Name Clashes. # 
# Warning: The node '220901_atest_modeling_v001_shapeEditorManager' still clashed with a node in the main scene.  Renaming to '_atest_modeling_v001_shapeEditorManager'. # 
# Warning: Edits on '220901_atest_modeling_v001_shapeEditorManager' may have been lost as a result of renaming. We strongly recommend the use of Namespaces to resolve Name Clashes. # 
# Warning: The node '220901_atest_modeling_v001_uiConfigurationScriptNode' still clashed with a node in the main scene.  Renaming to '_atest_modeling_v001_uiConfigurationScriptNode'. # 
# Warning: Edits on '220901_atest_modeling_v001_uiConfigurationScriptNode' may have been lost as a result of renaming. We strongly recommend the use of Namespaces to resolve Name Clashes. # 
# File read in  0.024 seconds.
# *** WRN: >>> { <openpype.hosts.maya.api.workfile_template_builder.MayaTemplateBuilder object at 0x000002B45DB3D948> }: [ No placeholders were found. ] ```

Scene outliner after loading the template file:
![image](https://user-images.githubusercontent.com/112623825/191943182-ee394539-8b0c-4249-a167-d9fc52164ebe.png)

also not sure if the Placeholder creator work as supposed to...gives me this when triggered:
![image](https://user-images.githubusercontent.com/112623825/191943500-e8d848ff-2a98-4f93-9c84-a608f6e963e9.png)

**Comment by iLLiCiTiT** [comment]
> also not sure if the Placeholder creator work as supposed to...gives me this when triggered:

I had typo there. Should be fixed now. @LiborBatek please try again.

**Review by jakubjezek001 — CHANGES_REQUESTED** [review]
image

==============================
cleanup_placeholder() takes exactly 2 arguments (3 given)
==============================
Traceback (most recent call last):
  File "C:\CODE\__PYPE\OpenPype\openpype\pipeline\workfile\workfile_template_builder.py", line 552, in populate_scene_placeholders
    placeholder_plugin.populate_placeholder(placeholder)
  File "C:\CODE\__PYPE\OpenPype\openpype\hosts\nuke\api\workfile_template_builder.py", line 186, in populate_placeholder
    self.populate_load_placeholder(placeholder)
  File "C:\CODE\__PYPE\OpenPype\openpype\pipeline\workfile\workfile_template_builder.py", line 1404, in populate_load_placeholder
    self.cleanup_placeholder(placeholder, failed)
TypeError: cleanup_placeholder() takes exactly 2 arguments (3 given)

**Review by jakubjezek001 — APPROVED** [review]
Works as it was before by the original PR. I believe in next pass, we should fix removing of used Placeholders, correctly reconnect loaded containers from placeholders.

**Comment by iLLiCiTiT** [comment]
@LiborBatek or @m-u-r-p-h-y can you check Maya?

**Comment by LiborBatek** [comment]
I have tested it again with following results:

First creating the placeholder for loading model family into my lookdev template file. With this I ve put the placeholder to "lookMain" subset and save it as an lookdev template file
image

Placeholder creator works normally now:
image

Creating lookdev workfile from template works ok and give me this result:
image

When trying to publish the look it gives me this warning:
image

later giving me this error msg:
image

**Comment by iLLiCiTiT** [comment]
> later giving me this error msg:

Note related to this PR.

**Pull request merged**
