### PR TITLE
Standalone Publish of textures family

### PR DESCRIPTION
**Pull request by kalisp**
3.0 version of https://github.com/pypeclub/OpenPype/pull/1747

Closes: pypeclub/client#115

### CODE REVIEW

**Review by jezscha — APPROVED** [review]
I am having troubles to collect. this sort of problem we have had before and this check should happen in a Validator. 
image

**Review by jezscha — CHANGES_REQUESTED** [review]
Accidentally hit approve before

**Comment by kalisp** [comment]
Fixed defaults

**Review by jezscha — CHANGES_REQUESTED** [review]
image

if I try to plublish following data
image

**Review by jezscha — APPROVED** [review]
image

In case of second version, I have add textures and .spp workfile, but validator didnt let me publish even those txtures were available.

**Review by jezscha — CHANGES_REQUESTED** [review]
Accidentally hit approve before

**Review by jezscha — APPROVED** [review]

**Pull request merged**
