### PR TITLE
Maya - added transparency into review creator

### PR DESCRIPTION
**Pull request by kalisp**
## Brief description
Transparency configuration was missing from `CreateReview`

## Testing notes:
1. Create camera in Maya scene and Create Review family
2. check created review group, there should be new item to select transparency
3. publish and check that selected transparency was applied

### CODE REVIEW

**Comment by kalisp** [comment]
Should `CreateReview` class attributes added to Settings? (`keepImages`, `isolate`, 'imagePlane`, `transparency`)

**Comment by antirotor** [comment]
> Should `CreateReview` class attributes added to Settings? (`keepImages`, `isolate`, `imagePlane`, `transparency`)

I don't think so, those are set usually per scene. Except maybe transparency. Any thought about that @tokejepsen ?

**Comment by tokejepsen** [comment]
> I don't think so, those are set usually per scene. Except maybe transparency. Any thought about that @tokejepsen ?

Yeah, we set it in the scene usually, since its dependent on the project/shot/task. I guess eventually if you could have project/shot/task settings, then we might configure it on a larger set of tasks, but for now setting it in the scene works well.

**Review by antirotor — APPROVED** [review]
works for me!

**Comment by m-u-r-p-h-y** [comment]
another example of arbitrary attributes cluttering the code and the UI . . .

**Comment by tokejepsen** [comment]
> another example of arbitrary attributes cluttering the code and the UI . . .

What was the solution to this?

**Pull request merged**
