### PR TITLE
Added endpoint for configured extensions

### PR DESCRIPTION
**Pull request by kalisp**
Closes https://github.com/pypeclub/OpenPype/issues/2182

~(Not yet deployed to test server!)~

Currently webpublisher had extensions for allowed files hardcoded.

This implements new endpoint `api/webpublish/configured_ext/{}` which requires one argument with name of the project and
returns list of extensions that are configured in `CollectPublishedFiles`

### CODE REVIEW

**Comment by mkolar** [comment]
Task linked: [OP-1950 Add endpoint about configured extensions for webpublisher](https://app.clickup.com/t/6658547/OP-1950)

**Comment by martastain** [comment]
WebPublisher uses different lists of extensions for single files and sequences. Shoudn't the endpoint provide both? e.g.
```json
{
    "file_exts" : ["jpg", "exr", "png", "tvp", "aep"],
    "sequence_exts : ["jpg", "exr", "png"]
}
```

**Comment by martastain** [comment]
Update: there is also a list for extensions valid for "studio processing".

**Comment by kalisp** [comment]
Extension now returns:
{
    "file_exts" : ["jpg", "exr", "png", "tvp", "aep"],
    "sequence_exts" : ["jpg", "exr", "png"],
    "studio_exts": ["tvpp","psd","tvp","psb"]
}

**Review by 64qam — APPROVED** [review]

**Pull request merged**
