### PR TITLE
Validate Maya Rig produces no cycle errors

### PR DESCRIPTION
**Pull request by BigRoy**
## Brief description

Cycles in Maya's dependency graph are a no go 99.9% of the time. They are inconsistent in general but even worse in Parallel Evaluation mode - they can't be relied on and should be avoided when possible.

This validator ensures the rig itself doesn't produce a cycle error.

### CODE REVIEW

**Comment by tokejepsen** [comment]
Noice! Think generally cycles are unwanted so maybe this should operate on all families?

**Comment by BigRoy** [comment]
We could, but I've never seen it be an actual problem in production on that level. First, most other publishes tend to not result in Maya files and thus the cycles aren't a problem in the resulting file. Second, there have been cases where a scene did give cycle errors, the user in production had no "willpower?" 😆 to fix it and the resulting output was fine for the production needs so no harm caused.

But technically nothing is holding us back on renaming this to *Cycle Errors* instead of *Rig Cycle Errors* and potentially having the default family setting exposed in OpenPype Admin Settings and have it set to `families = ["rig"]` by default so one could alter it to anything.

I wonder what others think.

**Comment by mkolar** [comment]
>But technically nothing is holding us back on renaming this to Cycle Errors instead of Rig Cycle Errors and potentially having the default family setting exposed in OpenPype Admin Settings and have it set to families = ["rig"] by default so one could alter it to anything.

I'd say that would be the best way to go about it. Default to rig only is reasonable, but I can potentially see situations where it would be useful to add more families. Rare, but possible.

**Comment by BigRoy** [comment]
Refactored this to be less specific in name to "rig" family and exposed settings for it in Admin settings.

### Passed tests

It defaults to **enabled, not optional and applied to "rig" family only**.
I've tested it with disabling it, disabling/enabling optional, adding new families and removing "rig" family. All worked.

Then also double checked the validator. Here's some code to produce a test scene in Maya:
```python
import avalon.api
import openpype.lib
from maya import cmds


def create(Creator, name, members):
    """Create creator for current asset with name + add members"""
    # note: the create method does not "return" the publish instance so for now 
    # we use "useSelection" to add the members - since otherwise it's non trivial.
    options = {"useSelection": True}
    with avalon.maya.maintained_selection():
        cmds.select(members, replace=True, noExpand=True)
        container = avalon.api.create(Creator, 
                                      name=name, 
                                      asset=asset, 
                                      options=options)


# Create three meshes with cycle error between cube + sphere
cube = cmds.polyCube(name="cube_GEO", constructionHistory=False)[0]
sphere = cmds.polySphere(name="sphere_GEO", constructionHistory=False)[0]
cone = cmds.polyCone(name="cone_GEO", constructionHistory=False)[0]

# Create a cycle between cube <-> sphere.
cmds.connectAttr(cube + ".translateY", sphere + ".translateY")
cmds.pointConstraint(sphere, cube)

# Create some instances to do some validations
Creator = openpype.lib.get_creator_by_name("CreateRig")
asset = avalon.api.Session["AVALON_ASSET"]

# 1. Ensure cube + sphere produce cycle and are detected by validator
#    should error, on get_invalid() this should NOT include cone.
create(Creator, name="rigWithCycleError", members=[cube, sphere])

# 2. Ensure cube + sphere produce cycle but are NOT detected by validator when not in the related instance.
#    should PASS.
create(Creator, name="rigNoCycleErrors", members=[cone])

# 3. Ensure cone is not detected amongst the cycle when others do produce cycle.
#    should error, on get_invalid() this should NOT include cone.
create(Creator, name="rigWithCycleAndNoCycleErrors", members=[cube, sphere, cone])

```

These all worked as expected. 👍 

Note that Maya does have quite some settings for when to check for cycle errors on specific nodes, e.g. including checks with children, etc. And even a time limit to check for. So it's worthwhile to also check some more complex cycles.

Here are some test cases for those:
```python
# Produce a cycle over a longer series of nodes

# Force clean current scnene (WARNING: This clears your current scene!)
cmds.file(force=True, new=True)


# Create long chain of nodes that produce a cycle
nodes = []
for i in range(300):
    node = cmds.createNode("transform", name="foo{}".format(i))
    nodes.append(node)
    
    if i > 0:
        # Daisychain translateX between all nodes
        previous = nodes[i-1]
        cmds.connectAttr(previous + ".translateX", node + ".translateX")
        
   
# Constrain first to last
cmds.pointConstraint(nodes[-1], nodes[0]) 
cmds.select(nodes, noExpand=True, replace=True)
plugs = cmds.cycleCheck(all=False,
                        list=True)

assert plugs

# Delete the first node so the cycle is gone
# (We don't delete the last because maya by default also deletes the constrained object)
cmds.delete(nodes.pop(0))
cmds.select(nodes, noExpand=True, replace=True)
plugs = cmds.cycleCheck(all=False,
                        list=True)

assert not plugs
```

This also worked.
Some more:
```python


# Create pointConstraint <-> pointConstraint cycles
a = cmds.createNode("transform", name="a")
b = cmds.createNode("transform", name="b")
cmds.pointConstraint(a, b)
cmds.pointConstraint(b, a)

cmds.select([a, b], noExpand=True)
plugs = cmds.cycleCheck(all=False,
                        list=True)
print(plugs)
assert plugs

# Create orient -> parent constraint -> direct rotate connection cycle
a = cmds.createNode("transform", name="a")
b = cmds.createNode("transform", name="b")
c = cmds.createNode("transform", name="c")
cmds.orientConstraint(a, b)
cmds.parentConstraint(b, c)
cmds.connectAttr(c + ".rotate", a + ".rotate")

cmds.select([a, b, c], noExpand=True)
plugs = cmds.cycleCheck(all=False,
                        list=True)
print(plugs)
assert plugs
```
_These later ones I solely tested by the command that the validator triggers, assuming the validator triggers it just as nicely. It should be relatively portable to include in test cases once testing platform is in place._


### Failed tests: Uncaptured case?
Perform a cycle check with less straight of a connection, e.g. not translate to translate to translate, but `worldMatrix[0]`, decompose it and pass it back in to translate.
```python
# Force clean current scnene (WARNING: This clears your current scene!)
cmds.file(force=True, new=True)

cmds.loadPlugin("matrixNodes", quiet=True)
a = cmds.createNode("transform", name="a")
b = cmds.createNode("transform", name="b")
decompose = cmds.createNode("decomposeMatrix")
cmds.connectAttr(a + ".worldMatrix[0]", decompose + ".inputMatrix")
cmds.connectAttr(decompose + ".outputTranslate", b + ".translate")
cmds.connectAttr(b + ".translate", a + ".translate")


cmds.select([a, b], noExpand=True, replace=True)
plugs = cmds.cycleCheck(all=False,
                        list=True)
assert plugs
```
And here things got interesting - since in my mind this is definitely a cycle error. But since here an `AssertionError` got raised and it didn't pass it didn't capture it. However, no combination of settings for `cmds.cycleCheck` actually ended up capturing this particular case. Nonetheless whenever you select node `a` in the scene Maya does print this:
```
// Warning: Cycle on 'b.translate' may not evaluate as expected.  (Use 'cycleCheck -e off' to disable this warning.) // 
```

So somehow Maya is able to detect a cycle error, but the command itself doesn't seem to return it.

The same happens in Maya 2022 when trying this with the new `offsetParentMatrix` in the mix. It doesn't capture it. The nice thing about this case however is that in Maya itself, you can actually move one of the cubes (since translates are not blocked) and see the cycle happen in real-time. Plus the cycle error being spewed out into the script editor.
```python
cmds.loadPlugin("matrixNodes", quiet=True)
a = cmds.createNode("transform", name="a")
b = cmds.createNode("transform", name="b")
decompose = cmds.createNode("decomposeMatrix")
cmds.connectAttr(a + ".worldMatrix[0]", decompose + ".inputMatrix")
cmds.connectAttr(decompose + ".outputTranslate", b + ".translate")
cmds.connectAttr(b + ".worldMatrix[0]", a + ".offsetParentMatrix")


cmds.select([a, b], noExpand=True, replace=True)
plugs = cmds.cycleCheck(all=False,
                        list=True)
print(plugs)
```

The documentation of [`maya.cmds.cycleCheck`](https://help.autodesk.com/cloudhelp/2022/ENU/Maya-Tech-Docs/CommandsPython/cycleCheck.html) does state some more things about some cycles not being able to be detected unless in the "Evaluation Time Cycle":
>  Note that it is possible for evaluation cycles to occur even where no DG connections exist. Here are some examples:
> 
> 1) Nodes with evaluation-time dependent connections: An example is expression nodes, because we cannot tell what an expression node is actually referring to until it is evaluated, and such evaluation-time dependent nodes may behave differently based on the context (e.g. time) they are evaluated at. If you suspect a cycle due to such a connection, the best way to detect the cycle is through manual inspection.
> 
> 2) Cycles due to DAG hierarchy: noting that DAG nodes are implicitely connected through parenting, if a child DAG node connects an output into the input of a parent node, a cycle will exist if the plugs involved also affect each other. In order to enable detection of cycles involving the DAG, add the -dag flag to the command line.
>
> Note also that this command may incorrectly report a cycle on an instanced skeleton where some of the instances use IK. You will have to examine the reported cycle yourself to determine if it is truly a cycle or not. The evaluation time cycle checking will not report false cycles. 

### Conclusion

It's definitely better than nothing since it does capture some cases. However, we might want to make sure we're all aware this currently isn't the holy grail. The `cycleCheck` being done is purely a plug-based cycle check and it fails to capture some more complicated cases where potentially maya itself does not have an `attributeAffects` relationship setup.

I'd say the PR is still good to go - albeit we might want to add a disclaimer or improve the docstring that it doesn't capture all cycle cases - e.g those that are only found in time based cycles instead of more direct plug-based cycles.

**Comment by BigRoy** [comment]
Here's a custom method to actually capture those other cases that `maya.cmds.cycleCheck` failed to return too.

```python
from maya import cmds
import contextlib


@contextlib.contextmanager
def capture_cycle_errors():
    """Capture the plugs in Cycle Error warnings.
    
    During this context "Cycle on 'x' may not evaluate as expected"
    are captured and 'x' is extracted as plugs in the yielded list.
    
    """
    import maya.OpenMaya as om
    
    plugs = []
    def _callback(nativeMsg, messageType, data):
        if messageType != om.MCommandMessage.kWarning:
            # We only care about warnings
            return
            
        if not nativeMsg.startswith("Cycle on '"):
            # Consider only Cycle on messages
            return
            
        plug = nativeMsg.split("'")[1]
        plugs.append(plug)
        
    id = om.MCommandMessage.addCommandOutputCallback(_callback, None)
    
    # Make sure evaluation time cycle check is enabled
    original = cmds.cycleCheck(query=True, evaluation=True)
    cmds.cycleCheck(evaluation=True)
    
    try:
        yield plugs
    finally:
        om.MMessage.removeCallback(id)
        cmds.cycleCheck(evaluation=original)
        
      
def cycle_check(nodes):
    
    # Include history for the nodes since it makes
    # the following check much more accurate to
    # correctly log during the capture block
    nodes = list(set(cmds.listHistory(nodes)))
    
    with capture_cycle_errors() as plugs:    
        # Force the full DG evaluation
        cmds.dgdirty(nodes)
        cmds.dgeval(nodes)
        
    return plugs
      

# Test    
cmds.file(new=True, force=True)
cmds.loadPlugin("matrixNodes", quiet=True)
a = cmds.createNode("transform", name="a")
b = cmds.createNode("transform", name="b")
decompose = cmds.createNode("decomposeMatrix")
cmds.connectAttr(a + ".worldMatrix[0]", decompose + ".inputMatrix")
cmds.connectAttr(decompose + ".outputTranslate", b + ".translate")
cmds.connectAttr(b + ".worldMatrix[0]", a + ".offsetParentMatrix")
    
nodes = [a, b]
plugs = cycle_check(nodes)

# Our check:
print(">> cycle_check(nodes)")
print(plugs)
# THIS FINDS THE PLUG!

# maya.cmds.cycleCheck
print(">> maya.cmds.cycleCheck(all=True, list=True)")
print(cmds.cycleCheck(all=True, list=True))
# MAYA FAILS TO FIND THE PLUG WITH THIS.
```

However, this of course tends to be a lot slower due to it triggering a full evaluation of every node involved in the rig. Here's a quick speed difference on a biped rig:
```
>> cycle_check(nodes)
2.2677080631256104
>> maya.cmds.cycleCheck(all=True, list=True)
0.17589807510375977
```

**Comment by mkolar** [comment]
I don't have a serious production rig on hand, but from quick tests, I would be happy enough with merging this and dealing with any special and more complex case if they arise.

**Review by mkolar — APPROVED** [review]

**Comment by mkolar** [comment]
but, we have a bunch of conflicts with recent merges

**Comment by BigRoy** [comment]
> but, we have a bunch of conflicts with recent merges

Should be resolved.

**Pull request merged**
