### PR TITLE
Maya capture 'isolate_view' fix + minor corrections

### PR DESCRIPTION
**Pull request by 2-REC**
- Handling of Maya capture 'isolate_view' preset (was ignored)
- Removal of unused 'capture_gui' module
- Minor changes (cleaning and typo)

### CODE REVIEW

**Review by mkolar — APPROVED** [review]
thanks. Seems that it's working as intended.

**Comment by mkolar** [comment]
@2-REC there was a small change in the colour setting in maya playblast, which causes conflict in maya/api/lib.py

It should be trivial to fix and I'll merge right after.

**Comment by mkolar** [comment]
Just realised this is in your fork :D so I can't fix the conflict. @2-REC If you merge the latest develop to your branch you can fix it easily like this.
image

**Comment by 2-REC** [comment]
I have made the change to avoid the merge conflict.
The conflict was caused by this specific line in 'openpype/hosts/maya/api/lib.py':
```python
<<<<<<< HEAD
            disp_options[key] = preset['Display Options'][key]
=======
            disp_options[key] = preset[id][key]
>>>>>>> bc/fix/capture
```
It seems weird that Git cannot solve this, it is a pretty basic change (replace *'Display Options'* by *id*).
Especially that the same change was made 2 lines earlier and didn't create a conflict.

**Comment by mkolar** [comment]
>(And even weirder, the conflict didn't happen in pype2...)

we added those colour options on following lines in 3.0 so 2.x wouldn't pick it up. I think we have accidentally added a space or something like that on the line you had to fix, so git got confused. Luckily non-essential part so no worries.

Thanks for the fix.

**Pull request merged**
