### PR TITLE
Maya : add option to not group reference in ReferenceLoader

### PR DESCRIPTION
**Pull request by BenoitConnan**
Options added :
- attach_to_root : wether or not a group should contain reference

---
name: Feature request
about: Suggest an idea for this project
title: Add options to ReferenceLoader
labels: enhancement
assignees: ''
---

**Is your feature request related to a problem? Please describe.**
When an asset is referenced, a group  `subset`_`asset`_:_GRP is created
For our workflow already using a root node with a special name this group is
redundant and even an annoyance.

**Describe the solution you'd like**
Loaders have the possibility to receive options yet none were developped for ReferenceLoader.
So the pull request is about adding "attach_to_root" as an option.
Option is set by default as True to keep legacy loader behaviour

**Describe alternatives you've considered**
Huu ... Making another ReferenceLoader not grouping ?

### CODE REVIEW

**Review by antirotor — CHANGES_REQUESTED** [review]
I am not sure how it is supposed to work. Either it is missing options defined in:

https://github.com/Ellipsanime/OpenPype/blob/7e04079151479548daf15ec81768c454935c71d3/openpype/hosts/maya/api/plugin.py#L91-L104

Or perhaps it should be configurable via Settings?

**Comment by BenoitConnan** [comment]
> I am not sure how it is supposed to work. Either it is missing options defined in:
> 
> https://github.com/Ellipsanime/OpenPype/blob/7e04079151479548daf15ec81768c454935c71d3/openpype/hosts/maya/api/plugin.py#L91-L104
> 
> Or perhaps it should be configurable via Settings?

Hi,
I'm not sure to get what you meant.
Should i add a qargparse.Boolean to options of ReferenceLoader ?
If so then i can't help to notice that options of ReferenceLoader is never used anywhere.

Maybe i'm missing something ?

**Comment by antirotor** [comment]
> Maybe i'm missing something ?

 what I meant was  adding it here:
image

**Comment by BenoitConnan** [comment]
Oh, i see. I didn't know this was a thing. I was monkey patching loading to set options. That way better.

Well, it's in now :)

**Review by antirotor — APPROVED** [review]
Good work, thanks!

**Pull request merged**
