### PR TITLE
Houdini: simple HDA workflow

### PR DESCRIPTION
**Pull request by antirotor**
This is adding simple Houdini Digital Asset (hda) workflow to OpenPype.

:gear: **Depends on:** pypeclub/avalon-core#371
| --- |

### CODE REVIEW

**Comment by mkolar** [comment]
This could do with some documentation ;)

**Review by mkolar — CHANGES_REQUESTED** [review]
I'm hitting a lot of errors about trying to select non-existent nodes. I have a feeling it might be that I'm working with the HDA differently than intended so I'll wait for the docs

**Comment by icyvapor** [comment]
Hey guys, 

running off the latest 'develop' I see the same error Milan posted above still.. what did I miss?  
Also when I try to publish it out, it failed on this line: [https://github.com/pypeclub/OpenPype/blob/develop/openpype/hosts/houdini/plugins/publish/extract_hda.py#L21]

where the `hda_def` is None.  

I didn't find anything particular I'm missing about HDA creation & publish. I'll continue troubleshooting on my end in the meantime. Thanks!!

**Comment by antirotor** [comment]
> Hey guys, 
> 
> running off the latest 'develop' I see the same error Milan posted above still.. what did I miss?  
> Also when I try to publish it out, it failed on [this line](https://github.com/pypeclub/OpenPype/blob/develop/openpype/hosts/houdini/plugins/publish/extract_hda.py#L21), where the `hda_def` is None.  
> 
> I didn't find anything particular I'm missing about HDA creation & publish. I'll continue troubleshooting on my end in the meantime. Thanks!!

Make sure you have updated avalon-core. This happens because old avalon is trying to maintain selection on nodes that are already moved into created hda.

**Comment by icyvapor** [comment]
Ah okay, seems the submodule in develop branch is outdated. 
I'll probably put in a PR once I got it working locally. 

Thanks!

> > Hey guys,
> > running off the latest 'develop' I see the same error Milan posted above still.. what did I miss?
> > Also when I try to publish it out, it failed on [this line](https://github.com/pypeclub/OpenPype/blob/develop/openpype/hosts/houdini/plugins/publish/extract_hda.py#L21), where the `hda_def` is None.
> > I didn't find anything particular I'm missing about HDA creation & publish. I'll continue troubleshooting on my end in the meantime. Thanks!!
> 
> Make sure you have updated avalon-core. This happens because old avalon is trying to maintain selection on nodes that are already moved into created hda.

**Comment by icyvapor** [comment]
Hmm I pulled down the latest 'main' of avalon-core, but still got exactly the same errors. 

image

EOD here, so mental energy is running low.. Cheers!

**Comment by antirotor** [comment]
> Hmm I pulled down the latest 'main' of avalon-core, but still got exactly the same errors.

Can you provide more information how to replicate? Houdini version, step by step what you are doing that lead to this error? Thanks

**Comment by icyvapor** [comment]
Test was done in Houdini FX 18.5. (others may use core)

I was just doing the simplest HDA workflow: 

1. create workfile
2. create a node, keeping it selected
3. OpenPype->create, select HDA in the menu
4. then I saw the first error, though the hda did seem to be created: 
 
openpype_hda_error1

5. run 'publish': 
openpype_hda_error2

I'm not super familiar with Houdini, hopefully I didn't miss anything obvious? I'll also do some instrumentation to see what's going on. 

Thanks!!

**Comment by icyvapor** [comment]
A bit more progress : 
- If I create a HDA first, and Openpype 'create' that as hda, then Pyblish can reach the integration step and failed there:  

image

- From reading the user docs, it feels that a hda node doesn't need to be created before OpenPype-create. So can users selected some node(s) and let Openpype create a HDA for publishing?  

If you guys want I can move this to discord :joy:

**Comment by antirotor** [comment]
This error is related to completely different bug :) probably fixed by #2322 - try to use latest develop

It works like this:

- if you select non-hda nodes, it will pick them and create new hda node from them
- if you select already existing hda node it will publish this node without changes

**Comment by icyvapor** [comment]
@antirotor 
Thanks for your reply!
I was able to Openpype create+publish an existing hda without issue, with the latest 'develop' branch.

For the first use case you described above, it still gives me the same error at creation and publish, as I mentioned above. But I read @mkolar 's original issue description, it seems the requirements were simply to publish/load a hda, rather than taking care of the hda node generation at the same time. It probably will suffice our workflow, just to let know of this limitation.

**Comment by antirotor** [comment]
> For the first use case you described above, it still gives me the same error at creation and publish, as I mentioned above

I've just tested it and it works:
hda

I would love to know why it isn't in your case...

**Comment by icyvapor** [comment]
Ah it's interesting: 

I noticed you were selecting two pieces of geo to create the HDA, where I was always testing with one. 
Did another quick test, sure enough: I can repeat  the issue only shows up when there's one single node to be packaged into hda. (Not super Houdini savvy, I don't know whether creating hda from single node is a bad practice.. I thought it should be allowed?)


image

image

Any case, this doesn't block us from using the HDA workflow, we have some internal HDA creation tools already. And I gotta move on to other parts of our testing, so it'll be production ready sooner. Thanks for the help and support on this!

**Comment by antirotor** [comment]
FYI this is fixing your problem #2350

**Pull request merged**
