### PR TITLE
Maya: RenderSettings set default image format for V-Ray+Redshift to exr

### PR DESCRIPTION
**Pull request by BigRoy**
## Brief description

 Set default image format for V-Ray+Redshift to `exr` instead of `png` and `iff` in OP settings.

## Testing notes:

1. Test setting default rendersettings with V-Ray and Redshfit.

### CODE REVIEW

**Comment by Allan-I** [comment]
Off the top of my head I don't remember precisely but I think Redshift required a list index to be passed as opposed to a file format string.  But I could be wrong

**Comment by BigRoy** [comment]
> Off the top of my head I don't remember precisely but I think Redshift required a list index to be passed as opposed to a file format string. But I could be wrong

That's good to know, but that logic hasn't changed. [It's still doing that conversion from settings extension name to index](https://github.com/pypeclub/OpenPype/blob/a2fbb472b4f85ab9ac996d73b34dc8efcfd0b4c8/openpype/hosts/maya/api/lib_rendersettings.py#L162-L163).

This only touches the default setting.

**Comment by Allan-I** [comment]
> > Off the top of my head I don't remember precisely but I think Redshift required a list index to be passed as opposed to a file format string. But I could be wrong
> 
> That's good to know, but that logic hasn't changed. [It's still doing that conversion from settings extension name to index](https://github.com/pypeclub/OpenPype/blob/a2fbb472b4f85ab9ac996d73b34dc8efcfd0b4c8/openpype/hosts/maya/api/lib_rendersettings.py#L162-L163).
> 
> This only touches the default setting.

Oh damn yeah I'd forgotten writing that, yes sir that works just fine

**Review by Allan-I — APPROVED** [review]
LGTM!

**Pull request merged**
