### PR TITLE
General: Multilayer EXRs support

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Description
Add support for multilayer exrs for review, burnins and thumbnail creation.

## Changes
- moved transcoding related functions into `openpype/lib/transcoding.py`
- do multilayers check per representation instead of per instance
- multilayer check was merged with dwaa and dwab check
    - decompress related functions are included in new ones
    - `should_convert_for_ffmpeg` replaces `should_decompress`
    - `convert_for_ffmpeg` replaces `decompress`
- the check is currently done only for `.exr`
- oiiotool must be available to be able do the check
    - this is limiting MacOS as we don't have oiio build for darwin so all exr conversions are skipped
- process methods of extractors were split into 2 or 3 methods (a little bit less spaghetti code)

## Questions
- should we "try use ffmpeg" without conversion on MacOs?

### CODE REVIEW

**Comment by mkolar** [comment]
Task linked: [OP-2045 Preview for multilayer exrs](https://app.clickup.com/t/6658547/OP-2045)

**Comment by antirotor** [comment]
About mac 🍎 - I am wondering if we can use [Homebrew](https://formulae.brew.sh/formula/openimageio) of oiio as we already are using Homebrew for the building process... But this is probably note for another issue.

**Comment by iLLiCiTiT** [comment]
> I am wondering if we can use Homebrew of oiio as we already are using Homebrew for the building process... But this is probably note for another issue.

It is offtopic and I think we can. But I'm afraid it won't be compatible across all versions of OSx systems.

**Comment by antirotor** [comment]
It does work as far as I could test it. I had to make some fixes in Maya / Deadline part so it could be tested there. So I am approving it and if someone else can test it in Maya, I think we should merge it.

**Review by antirotor — APPROVED** [review]

**Pull request merged**
