### PR TITLE
Standalone Publish Textures

### PR DESCRIPTION
**Pull request by kalisp**
Requires: https://github.com/pypeclub/pype-config/pull/110

Closes: https://github.com/pypeclub/client/issues/115

Sample data based on delivered examples: (updated 9.7.2021)
[correct.zip](https://github.com/pypeclub/OpenPype/files/6792822/correct.zip)

(Test zip file contains multiple workfiles (to test `.mra` and `.spp` together, or separately), to test multiple published textures.
Multiple versions (to test validation of mismatched versions.)
Zip also contains example of broken file name (`correct\corridorMain_v001_broken_file_name_totally_raw_1001.exr`) to test validation on name pattern.)

### CODE REVIEW

**Comment by kalisp** [comment]
Implemented validations requested during presentation.

Dummy files for testing based on provided test data naming convention:
[correct.zip](https://github.com/pypeclub/OpenPype/files/6732811/correct.zip)

**Review by jezscha — APPROVED** [review]
great work!

**Comment by kalisp** [comment]
Deployed to the client on 1st of July for testing.

**Comment by kalisp** [comment]
Client requested splitting validation into 4 separate.
New test files because of changes to naming pattern.

**Comment by 64qam** [comment]
Looks good

**Review by jezscha — APPROVED** [review]
please fix following:
- labels for validators into easyer to read style
- validators are in context plugins rather then in instance

**Review by jezscha — CHANGES_REQUESTED** [review]
as the comment above

**Review by jezscha — CHANGES_REQUESTED** [review]
image

When I haven't added a workfile no validator had fired up - which is not a expected behaviour. It seems that the validator responsible for this check, is set on wrong family.

**Comment by jezscha** [comment]
> 2 validators didn't kick in, because they are only meant for 'workfile' family:
> 
> * workfile has resources (optional)
> * there are some textures present (and as there is collected instance for 'textures' there obviously are)

there should be two optional validators:
- one as you had said: workfile has resources
- second 'textures' family: textures has workfile (optional)

**Comment by kalisp** [comment]
Implemented as requested.

**Review by jezscha — APPROVED** [review]
ready for merge

**Pull request merged**
