### PR TITLE
Maya: Allow more data to be published along camera 🎥 

### PR DESCRIPTION
**Pull request by antirotor**
## Enhancement

This PR is releasing restrictions in camera extractors to allow more data to be published along with the camera. There is still validator that validates camera content and by default allows only camera to be passed down the line, but it can be set to allow more data. Usefull for proxy geometry / locators / pointcloud to be published with the camera.

### How to test it

in the Settings, there are new options for **Validate Camera Content** - `project_settings/maya/publish/ValidateCameraContents`. It can be disabled, it can be set as optional and also you can disable validating presence of shapes - in another words, disabling this option will allow more then cameras to pass this validator.

image

* Create camera instance and put for example box and camera under it
* Publish it with `Validate presence of shapes` **ON**
* Validator should trigger

---

* Disable `Validate presence of shapes` and try again
* Validator should pass and publish should be successful
* Loading camera as abc and ma should pull in camera and whatever geometry attached.

---

❔ not sure about the `Validate presence of shapes` as it is technically incorrect

### CODE REVIEW

**Comment by BigRoy** [comment]
1. Also - if we're allowing other arbitrary data in there doesn't this just make it a `pointcache` publish? What's the reason to not choose a `pointcache` family whenever needing additional geometry data with your cameras?
2. Even when allowing other shapes would we still want to validate that only a single camera is present?

**Comment by mkolar** [comment]
>If we're allowing other arbitrary data in there doesn't this just make it a pointcache publish? What's the reason to not choose a pointcache family whenever needing additional geometry data with your cameras?

The main reason is correct filtering and categorization in the loader. Having everything as pointcaches would become very confusing fairly quickly.

>Even when allowing other shapes would we still want to validate that only a single camera is present?

I think it does still make sense. This is about adding tracking or proxy geometry to the single camera. But it should still be recognizably a single camera.

**Comment by BigRoy** [comment]
> I think it does still make sense. This is about adding tracking or proxy geometry to the single camera. But it should still be recognizably a single camera.

I think this might also just be a +1 for implementing subset packages like #2724 which would actually solve this too?

**Comment by antirotor** [comment]
> > I think it does still make sense. This is about adding tracking or proxy geometry to the single camera. But it should still be recognizably a single camera.
> 
> I think this might also just be a +1 for implementing subset packages like #2724 which would actually solve this too?

I believe it solves it only partially. I can imagine integration with tracking software that is producing some geometry bound to specific camera - and it puts it to one single file (fbx or whatever). Without a full integration, you would drop such file into standalone publisher, select `Camera` and publish it.

It all depends how you feel about data being tightly bound to camera - proxy geo can live on its own, but some partial track, or pointcloud can be total nonsense without specific camera. So yes, in some cases Packages/Bundles would solve it, but I still believe that for particular workflows the camera and additional data are unseparable.

**Comment by antirotor** [comment]
Single camera is still validated by validator, I think extractors shouldn't care.

**Review by mkolar — APPROVED** [review]
I've tested all combination I could think of and all is working as expected

**Pull request merged**
