### PR TITLE
Global: Optimize OpenPype startup

### PR DESCRIPTION
**Pull request by BigRoy**
## Brief description

This is a draft PR to implement some changes to optimize some pieces from the OpenPype startup and is related to #2592 to allow less overhead when initializing to the environment.

I've gone ahead and started some minor tweaks. Some are just optimizations I figured could work glancing over the code (e.g. restructuring validate dir/zip logic) which only would make it faster in certain cases (for that particular case only when files would be missing).

The bigger improvement is to keep `global settings` around during startup and re-use it. With our network database [that ` get_openpype_global_settings` query alone](https://github.com/pypeclub/OpenPype/blob/1964e30246480bd33f4ebf9464130bba7bc14416/igniter/tools.py#L131-L161) takes 2+ seconds. So every time we avoid calling that would already gain us 2 seconds in our production use case. In `start.py` reducing the two calls to just one was that first step.

But that change should also be processed in Igniter `bootstrap_repos.py` so that the data could stay around more. (I've also not [refactored the use of `get_openpype_path_from_db` (changed signature)](https://github.com/pypeclub/OpenPype/commit/2373d13348f4d04e2da5063a74e618e696822bd6) in that bootstrap repos file which would be required for this to completely work in the build. (For now have been testing the changes running over the live code - less overhead/ faster results to check) But there's definitely optimization wiggle room in `bootstrap_repos` too.

---

Just setting up this **Draft** Pull Request to start a discussion. Would it be nice to change that signature of `get_openpype_path_from_db` like I did in this [commit](https://github.com/pypeclub/OpenPype/commit/2373d13348f4d04e2da5063a74e618e696822bd6).

Best case scenario the logic remains simple but we hit the database as little as possible.

### CODE REVIEW

**Comment by BigRoy** [comment]
Oddly enough [this function also takes two seconds](https://github.com/pypeclub/OpenPype/blob/1964e30246480bd33f4ebf9464130bba7bc14416/igniter/tools.py#L52-L86). That seems long.

Just this:
```python
    client = MongoClient(cnx, **kwargs)
    client.server_info()
    with client.start_session():
        pass
    client.close()
```
Takes 2 seconds. That seems extreme?
That makes me think getting the global settings itself isn't actually that slow - it's just making that temporary connection?

**Comment by iLLiCiTiT** [comment]
@BigRoy is this still a draft?

**Comment by BigRoy** [comment]
Yes, this will currently FAIL in the `bootstrap_repos.py` as not all usages are refactored to use the new `settings` signature for `get_openpype_path_from_db`.

We could also refactor to make an extra function `get_openpype_path_from_settings(settings)` and keep the old `get_openpype_path_from_db(url)` and use `get_openpype_path_from_settings(settings)` inside the _from db_ function. That way this PR would work as is and we can refactor more of the logic where it's currently less trivial to do so down the line.

**Comment by iLLiCiTiT** [comment]
> We could also refactor to make an extra function get_openpype_path_from_settings(settings) and keep the old get_openpype_path_from_db(url) and use get_openpype_path_from_settings(settings) inside the from db function

This sounds good.

> since I'm not sure what can of worms that would open across different platforms

I think that `socket.gethostbyname` would break support of multi replica set urls which contain 2-n hosts and pymongo is resolving which is used.

**Comment by BigRoy** [comment]
@iLLiCiTiT made some more code changes - any chance you could test this? Might be best to completely make a new build, etc. since it also influences igniter?

**Comment by iLLiCiTiT** [comment]
Code looks ok and it seems that OpenPype is launching faster so good for me. @antirotor can you check the code changes primarily zip summary checks?

**Review by antirotor — APPROVED** [review]

**Pull request merged**
