### PR TITLE
Hiero: loaded clip was not set colorspace from version data

### PR DESCRIPTION
**Pull request by jezscha**
# testing notes
- open hiero at your testing timeline
- set one of clip for publishing to some crazy colorspace like `cineon` or `Alexa`
- publish the clip 
- open Loader and load the subset back to your timeline
- double click to the clip on timeline > properties bin should open
- look for `colorspace` attribute and see if it is the same as the one you had set previously
- result should be the same.

### CODE REVIEW

**Comment by 64qam** [comment]
When processing `open Loader and load the subset back to your timeline` it fails with error: 

```>>> [ Default Tags were set... ]
C:\Users\qam\pypeclub\pype3\pype\openpype\modules\ftrack\python2_vendor\arrow\arrow\arrow.py:28: DeprecationWarning: Arrow will drop support for Python 2.7 and 3.5 in the upcoming v1.0.0 release. Please upgrade to Python 3.6+ to continue receiving updates for Arrow.
  DeprecationWarning,
>>> [ Running 'LoadClip' on 'reviewsq01sh010' ]
>>> [ Loading clips: `reviewsq01sh010_plateReview_mp4` ]
Traceback (most recent call last):
  File "C:\Program Files\Nuke12.2v3\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\signature\loader.py", line 111, in seterror_argument
    return errorhandler.seterror_argument(args, func_name)
  File "C:\Program Files\Nuke12.2v3\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\signature\errorhandler.py", line 98, in seterror_argument
    func = eval(func_name, namespace)
  File "<string>", line 1, in <module>
NameError: name 'core' is not defined
Fatal Python error: seterror_argument did not receive a result```

**Comment by jezscha** [comment]
> When processing `open Loader and load the subset back to your timeline` it fails with error:
> 
> ```
> C:\Users\qam\pypeclub\pype3\pype\openpype\modules\ftrack\python2_vendor\arrow\arrow\arrow.py:28: DeprecationWarning: Arrow will drop support for Python 2.7 and 3.5 in the upcoming v1.0.0 release. Please upgrade to Python 3.6+ to continue receiving updates for Arrow.
>   DeprecationWarning,
> >>> [ Running 'LoadClip' on 'reviewsq01sh010' ]
> >>> [ Loading clips: `reviewsq01sh010_plateReview_mp4` ]
> Traceback (most recent call last):
>   File "C:\Program Files\Nuke12.2v3\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\signature\loader.py", line 111, in seterror_argument
>     return errorhandler.seterror_argument(args, func_name)
>   File "C:\Program Files\Nuke12.2v3\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\signature\errorhandler.py", line 98, in seterror_argument
>     func = eval(func_name, namespace)
>   File "<string>", line 1, in <module>
> NameError: name 'core' is not defined
> Fatal Python error: seterror_argument did not receive a result```
> ```

Thanks for reporting this, but this doesn't seem to be related to the PR in any way. Looks like some bug had been passed into `develop` branch.. Try the same testing steps on develop pelease.

**Comment by 64qam** [comment]
Hiero works without errors when I use the latest `develop` or `main` branches (both Pype and Avalon). Once I switch to this `bugfix/hiero-load-clip-colorspace` branch, Hiero fails with the error mentioned above.

**Comment by jezscha** [comment]
> Hiero works without errors when I use the latest `develop` or `main` branches (both Pype and Avalon). Once I switch to this `bugfix/hiero-load-clip-colorspace` branch, Hiero fails with the error mentioned above.

Nice catch dude, thanks! ;)

**Review by 64qam — APPROVED** [review]

**Pull request merged**
