### PR TITLE
Deadline Maya Alembic caching

### PR DESCRIPTION
**Pull request by tokejepsen**
This adds a `farm` attribute to animation objectsets. When this attribute is `True`, local extraction is disabled and a job is sent to Deadline for extraction/integration.

### CODE REVIEW

**Comment by mkolar** [comment]
I haven't managed to make this work on my end, but didn't dig deep into the code of it. it seem that the job is created on deadline and it runs for a while but not publish is created. However it looks like publish is then trying to again send it to farm :).

I think this might also clash with latest changes in deadline submitting. @antirotor could you please have a look at the code?

image

**Comment by antirotor** [comment]
Frst two errors are bitching about workfile not being published along. For some time we enforce workfile to be published whenever something goes through deadline - controlled by `use_published` setting. This must have prevented submtting jobs and probably caused the last error.

**Comment by mkolar** [comment]
@tokejepsen have you actually managed to make this to work on your end. I seem to be stuck in a loop on the farm, when it tries to submit itself to deadline again after caching. 

@antirotor you are right, but this is happening when the deadline job tries to create another deadline job :)

**Comment by tokejepsen** [comment]
Yeah, had it working. Will try it again when I get time.

**Comment by tokejepsen** [comment]
This is working again!

**Comment by tokejepsen** [comment]
This support pointcaches as well now.

**Comment by tokejepsen** [comment]
Added a fix for instances to add the `farm` and `priority` attributes. Dealing with `animation` families is tricky cause its not easy to re-create because it get created when loading a rig.

**Comment by mkolar** [comment]
Thanks I'll test it asap.

**Comment by mkolar** [comment]
Took me ages to get to this, but It totally brought a big smile to my face. Very nice! @tokejepsen thanks.

**Review by mkolar — APPROVED** [review]

**Comment by mkolar** [comment]
I"m only keeping it unmerged for right now, because we need to port it to 3.0 as well. Happy to do that on our end though.

**Comment by tokejepsen** [comment]
> I"m only keeping it unmerged for right now, because we need to port it to 3.0 as well. Happy to do that on our end though.

Would appreciate it happening on your end! Got no idea about 3.0 and dont wanna know until I have to :)

**Comment by mkolar** [comment]
> > I"m only keeping it unmerged for right now, because we need to port it to 3.0 as well. Happy to do that on our end though.
> 
> Would appreciate it happening on your end! Got no idea about 3.0 and dont wanna know until I have to :)

No worries. Almost done with it, just need to refactor a few bits a tiny bit.

**Comment by BigRoy** [comment]
At Colorbleed we have a solution which runs a scene publish in Deadline for Maya and Houdini. I wonder how this compares to that?

The only diff really was publishing with.a different target. :) It works for Alembics, Yeti caching, etc. It was a trivial implementation and only fails for things that dont work in batch mode of the host. (Such as playblasting being somewhat unreliable in Maya batch.)

When this issue/PR gets picked up again let me know. Then I can make sure to compare approach before.

**Comment by tokejepsen** [comment]
Yeah, we could generalize this workflow by embracing publishing targets.
The alembic publishing script is fairly generic already.

**Comment by BigRoy** [comment]
Just as a reference some notes on our implementation.

- The plug-ins that always need to run set no target at all. They'll run for all targets.
- [Here's the Integrator that only triggers when the target is `local`](https://github.com/Colorbleed/colorbleed-config/blob/18805e69de414341c2089fe40e1dcc44c0da2424/colorbleed/plugins/global/publish/integrate.py#L45) which is the default target on our end.
- [Here's the to Deadline submission target and submitter](https://github.com/Colorbleed/colorbleed-config/blob/18805e69de414341c2089fe40e1dcc44c0da2424/colorbleed/plugins/maya/publish/submit_maya_publish_deadline.py#L48)
- [Deadline just runs this `publish_instances` script for the host.]https://github.com/Colorbleed/colorbleed-config/blob/18805e69de414341c2089fe40e1dcc44c0da2424/colorbleed/scripts/publish_instances.py) This works in both Maya and Houdini (maybe more, but that's where we tested it.)
- [The `local` target is always set when installing the config](https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/__init__.py#L23-L25)
- It looks as if the publish job doesn't `install` Avalon but it actually does that automatically due to the startup process of the host (e.g. `userSetup.py` in Maya)

**Review by mkolar — APPROVED** [review]

**Comment by mkolar** [comment]
Considering that this is functional in v2 and it's been hanging in here for quite a while. I'd be up for merging it. We are now able to replicate this in v3 across the board I think, but it's a bit different logic. I'll keep this tagged as needing a convert to 3.x so it doesn't get forgotten about.

**Comment by tokejepsen** [comment]
Woop woop! Its been a life saver here with FX work.

**Pull request merged**
