### PR TITLE
General: Move workfiles functions into pipeline

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Brief description
Moved workfile related logic to `openpype.pipeline.workfile` content.

## Description
Workfile path resolving functionality like which anatomy template is used, or receiving last workfile path based on template and fill data, or handling of paths to custom template used as source for first version was moved to workfile specific file. Class `BuildWorkfile` was also moved to `openpype.pipeline.workfile.build_workfile`. Functionality to create and update workfile documents has been modified to use operations.

## Testing notes:
- [x] Last workfile on launch should be started (if enabled)
    - `project_settings/global/tools/Workfiles/last_workfile_on_startup`
- [x] Custom template as first workfile version is used (if enabled and path is set in settings)
    - available for nuke, tvpaint, photoshop, blender, aftereffects `project_settings/<host>/workfile_builder`
    - if one works then all work
- [x] It is possible to store artist note in workfiles tool
- [x] Workfile building works in nuke and maya (`project_settings/<host>/workfile_build/profiles`)
- [x] It is possible to use different workfiles templates (e.g. unreal has different workfile template)
     - `project_settings/global/tools/Workfiles/workfile_template_profiles`

### CODE REVIEW

**Comment by kalisp** [comment]
It is not opening last workfile (at least for PS and AE), it returns to v001 even if workfiles for much higher versions exist. (Tested it in develop and there it is opening last workfile correctly.)

**Review by kalisp — CHANGES_REQUESTED** [review]
It is not opening last workfile (at least for PS and AE), it returns to v001 even if workfiles for much higher versions exist. (Tested it in develop and there it is opening last workfile correctly.)

**Comment by iLLiCiTiT** [comment]
> It is not opening last workfile (at least for PS and AE), it returns to v001 even if workfiles for much higher versions exist. (Tested it in develop and there it is opening last workfile correctly.)

Should be fixed. I skipped all extensions if they don't start with dot instead of fixing them...

**Comment by kalisp** [comment]
Last workfile works.
Tried to test Workfile builder in Nuke, but couldnt figure how it should look like.

**Review by kalisp — APPROVED** [review]
Build workfile works in Nuke.

**Pull request merged**
