### PR TITLE
General: Show applications without integration in project

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Brief description
It is not possible to add new applications without implementation and add them to project to be able launch them from launcher (or ftrack).

## Changes
- removed unused `shell` from applications
- all applications can be added to project's applications even if does not have host implementation
- it is possible to define applications that have custom launch method so they are not visible on task automatically
- added new `Additional` group into system settings applications. Additional applications does not support host selection

## Testing notes:
1. Create new application group in applications with schemas
2. Store it's defaults
3. From that moment it is possible to add application to anatomy applications (add it to one project)
4. You should see the application in launcher tool and in ftrack

Resolves https://github.com/pypeclub/OpenPype/issues/2653

### Screenshot
image

### CODE REVIEW

**Comment by mkolar** [comment]
Task linked: [OP-2590 Applications without integration](https://app.clickup.com/t/6658547/OP-2590)

**Review by mkolar — APPROVED** [review]
I'm wondering if we could open this up to be tweakable without the need for code changed. Adding a category within application called `Additional` with no host implementation into the default applications, would let studios quickly add additional application without host implementation as it's variants. That might be sufficient on top of these changes to allow simple addition.

**Review by mkolar — APPROVED** [review]

**Review by mkolar — COMMENTED** [review]
Sorry I wanted to comment only, not approve yet :D

**Comment by iLLiCiTiT** [comment]
> Adding a category within application called Additional with no host implementation into the default applications, would let studios quickly add additional application without host implementation as it's variant

Added. It is not 100% "safe" (you can add `maya`) but I would not care about it until someone hit the issue...

**Comment by iLLiCiTiT** [comment]
> I've tried adding affinity and getting following

Fixed

**Review by mkolar — APPROVED** [review]

**Pull request merged**
