### PR TITLE
Maya: Enable thumbnail transparency on extraction.

### PR DESCRIPTION
**Pull request by tokejepsen**
## Brief description
Enable thumbnail transparency on extraction.

## Description
Missing transparency feature from playblast extraction.

## Additional info
The rest will be ignored in changelog and should contain any additional
technical information.

## Documentation (add _"type: documentation"_ label)
[feature_documentation](future_url_after_it_will_be_merged)

## Testing notes:
1. start with this step
2. follow this step

### CODE REVIEW

**Comment by LiborBatek** [comment]
Hi, Toke, sry could you describe the steps involved to test it...Im not sure which action does thumbnail is it done from ```review``` subset?
Thx, will test it then.
Libor

**Comment by tokejepsen** [comment]
> Hi, Toke, sry could you describe the steps involved to test it...Im not sure which action does thumbnail is it done from `review` subset? Thx, will test it then. Libor

Sorry yeah, that was lazy of me.

1. Create review in Maya.
2. Choose a different transparency algorithm from what the viewport uses.
3. Publish and check transparency on thumbnail for review.

**Review by LiborBatek — APPROVED** [review]
Done tests and works ok.
image

**Comment by LiborBatek** [comment]
viewport transparency was set to "simple" and for "review/thumbnail" was set to "Alpha Cut"...Published as set in review. All right.

**Pull request merged**
