### PR TITLE
Maya: Remove unused get current renderer logic

### PR DESCRIPTION
**Pull request by BigRoy**
## Brief description

The `renderer` variable wasn't used.

## Description

The [instance.data["renderer"] data was explicitly collected again further down in the code](https://github.com/pypeclub/OpenPype/blob/develop/openpype/hosts/maya/plugins/publish/collect_render.py#L290-L291) leaving the `renderer` variable collected here unused.

## Additional info

Since this code has been in there like that for a while (e.g. in [3.9.0 nightly](https://github.com/pypeclub/OpenPype/blob/CI/3.9.0-nightly.1/openpype/hosts/maya/plugins/publish/collect_render.py#L324-L325) and probably earlier too) I chose to simplify to just using the logic that ended up being used.

## Testing notes:
1. Test renderman functionality

### CODE REVIEW

**Comment by m-u-r-p-h-y** [comment]
Can we merge #3643 to this PR as it is failing on `Images File Rule` bug and can't test it properly because of it . . . 

thx!

**Review by m-u-r-p-h-y — COMMENTED** [review]
Can we merge #3643 to this PR as it is failing on `Images File Rule` bug and can't test it properly because of it . . .

thx!

**Comment by BigRoy** [comment]
@m-u-r-p-h-y should be fine to test now!

**Comment by m-u-r-p-h-y** [comment]
I double-checked I pulled the latest code in GitKr, but still got the error. 
What am I doing wrong?

image

**Comment by m-u-r-p-h-y** [comment]
just tested latest develop and it is passing through Images Rule validation successfully . . .

**Comment by BigRoy** [comment]
> I double-checked I pulled the latest code in GitKr, but still got the error.
> What am I doing wrong?

Must have been my bad. Seems it merged without fetching latest develop.

**Review by m-u-r-p-h-y — APPROVED** [review]
Maya 2022
RFM 24.4

submitting render to farm works as expected.

image

**Review by antirotor — APPROVED** [review]

**Pull request merged**
