### PR TITLE
General: Oiio conversion multipart fix

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Brief description
Don't define input channels if input is multipart exr.

## Description
When converting multipart exr for ffmpeg it can't handle definition of channels on input because there are multiple subimages which cause crash if oiiotool.

Extended few types in xml info result parsing and added ability to receive information about every subimage in exr.

## Additional information
The output has all subimages (which can be big exr) that is because ffmpeg then created transparent image without any content. Not sure why but it's an issue. Also if any subimage in the exr has attributes with invalid characters or too long value it would cause issues in ffmpeg too -> future enhancements.

## Testing notes:
1. It should be possible to convert multipart exr for ffmpeg (e.g. in extract review)

### CODE REVIEW

**Comment by antirotor** [comment]
Looks good but since we are messing up now with xml, shouldn't we parse it and work with it that way instead of hacking it as string?

**Comment by iLLiCiTiT** [comment]
> Looks good but since we are messing up now with xml, shouldn't we parse it and work with it that way instead of hacking it as string?

I don't know to which code is this related?

**Comment by LiborBatek** [comment]
Did test  in ```maya2022``` and ```arnold``` it Deadline job finnished normally without any errors and published all.

here is the scrncap of published data
image

however when played the mp4 review even thumbnail looked fine the vid is completely black...
image

**Comment by antirotor** [comment]
> > Looks good but since we are messing up now with xml, shouldn't we parse it and work with it that way instead of hacking it as string?
> 
> I don't know to which code is this related?

all lines like `if line == "</ImageSpec>":` - wouldn't be cleaner to use xml dom and not strings?

**Review by LiborBatek — CHANGES_REQUESTED** [review]
Not working fully. Pls see comments.

**Pull request merged**
