### PR TITLE
Simple tvpaint publish

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changes
- review instance is always created even if review is not in instances of workfile metadata
    - subset name is hardcoded to `"reviewMain"`
- instances without `"uuid"` in data are skipped on pyblish plugin toggle callback
- removed review creator
    - we should maybe keep this creator to be able change subset name of review?

Closes https://github.com/pypeclub/client/issues/67

### CODE REVIEW

**Comment by tokejepsen** [comment]
Sorry, dont quite get this. Can the user disable/toggle the review still in the Pyblish window?
Just wanna make sure users can publish faster by only outputting what is needed.

**Comment by mkolar** [comment]
> Can the user disable/toggle the review 
Yes of course. 

The point of this is to make it as easy a quick as possible for artists that maybe don't have full training, to open a scene, do some work and publish with simple review without having to use creator. Production request to make life easier for freelancers.

**Comment by tokejepsen** [comment]
> The point of this is to make it as easy a quick as possible for artists that maybe don't have full training, to open a scene, do some work and publish with simple review without having to use creator. Production request to make life easier for freelancers.

Sorry, yeah I get that and agree. Just wanna make sure advanced users still have options.

**Comment by mkolar** [comment]
@tokejepsen just noticed, that my "Yes, of course" got lost in the quote in the previous post. So just to make sure. Yes, it should be possible to disable the review just as any other instance ;)

**Review by mkolar — APPROVED** [review]
On a code from I'm happy with this. @64qam could you please check functionality?

**Review by 64qam — APPROVED** [review]

**Pull request merged**
