### PR TITLE
Enable write color sets on animation publish automatically

### PR DESCRIPTION
**Pull request by moonyuet**
## Brief description
Add the switching on/off option for write color sets in Create Cache in Openpype settings
image

## Description
Add the switching on/off option for write color sets in Create Cache in Openpype settings, which overrides the write color sets attributes in maya when creating point cache instance for the geometry. 
It is implemented for being consistent regarding to the same implementation of switching on/off options in Create Animation for maya.

### CODE REVIEW

**Review by m-u-r-p-h-y — APPROVED** [review]
It works as expected. Animation and Point Cache instances are created with proper values set from settings.

I would suggest unifying the naming in settings though. 

Cache -> Point Cache

image

**Comment by mkolar** [comment]
@moonyuet I agree with Murphy. all good, just please fix the label and the hound comments.

**Comment by moonyuet** [comment]
image
Get the name changed!

**Review by m-u-r-p-h-y — APPROVED** [review]
Nice! Ready to go . . .

**Pull request merged**
