### PR TITLE
Ftrack: Family to Asset type mapping is in settings

### PR DESCRIPTION
**Pull request by gabormarinov**
## Brief description
Added missing Family Mapping settings

### CODE REVIEW

**Comment by BigRoy** [comment]
Aside of allowing customizing the family mapping this also now allows to enable/disable the Plugin itself in admin settings, correct?

Is that something we want or could that cause problems if someone would disable the `IntegrateFtrackInstance` plugin?

**Comment by gabormarinov** [comment]
Yes, there's an enable/disable switch as well. All other FTrack plugin settings setup this way, I followed them. But of course it can be removed.

**Comment by gabormarinov** [comment]
Maybe @mkolar or @iLLiCiTiT can give us some guide?

**Comment by antirotor** [comment]
I am not sure about disabling IntegrateFtrackInstance. I guess it is integral part of ftrack module and you either want the whole ftrack module enabled or have it completely disabled? Of course, this cannot be done per project level so with this you could control it on project level, but the use case would be pretty niche I suppose.

**Comment by iLLiCiTiT** [comment]
There should not be enable checkbox on this plugin. If you want to disable ftrack per project you can "not add" ftrack families in Collect Ftrack Family.

**Comment by gabormarinov** [comment]
Roger, checkbox removed and added more defaults, now all current OpenPype families are mapped by default. The exception is "Render", but it is never synced to FTrack.

**Comment by iLLiCiTiT** [comment]
Please don't use tabs but 4 spaces and do not save default values modifying the file but use settings tool to do so.

**Comment by gabormarinov** [comment]
Done.

**Comment by iLLiCiTiT** [comment]
:) Check changes you've made in this PR. You've added space after all keys in the schema `{"key" : "value"}` which should be `{"key": "value"}` this is most likely style agreement we have and would be good to keep it consistent (and not change). Also you've manually saved the file with default values. I know that because of the change of last line in `openpype/settings/defaults/project_settings/ftrack.json`. If possible don't change json files with default values manually.

**Comment by gabormarinov** [comment]
Yep, sorry for the formatting changes. I actually saved the defaults from the settings editor, but copy/pasted the content of the file into the github editor to commit. I'll install some IDE soon to do proper commits, I just wanted to create a quick patch for now. I hope the formatting is ok now.

**Review by mkolar — APPROVED** [review]

**Review by iLLiCiTiT — APPROVED** [review]

**Pull request merged**
