### PR TITLE
General: Startup validations

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changes
- added startup validations to `start.py`
- currently FFmpeg and OpenImageIO executables are checked which raise `RuntimeError` if are not available
    - oiio tools are checked only for windows and linux
- this happens before arguments are handled (in `boot` function)
- show a message window if are not detected and not in headless mode (using tkinter)

### CODE REVIEW

**Comment by mkolar** [comment]
Task linked: [PYPE-1316 Validation on OpenPype start](https://app.clickup.com/t/6658547/PYPE-1316)

**Comment by kalisp** [comment]
Could we add some more logging to `_determine_mongodb`? That could be helpful for Deadline installations (without OPENPYPE_MONGO it could explode in a weird way.)

**Review by mkolar — COMMENTED** [review]
Can we also remove the ffmpeg publish validator at the same time please?

**Comment by iLLiCiTiT** [comment]
> Could we add some more logging to _determine_mongodb? That could be helpful for Deadline installations (without OPENPYPE_MONGO it could explode in a weird way.)

That's not quite issue of this PR + IDK where it crashes. If you know do a PR.

> Can we also remove the ffmpeg publish validator at the same time please?

That's already done (is there any other than validate ffmpeg installed?).

**Comment by mkolar** [comment]
>That's already done (is there any other than validate ffmpeg installed?).

my bad, you are right.

**Comment by mkolar** [comment]
>That's not quite issue of this PR + IDK where it crashes. If you know do a PR.

agreed. we should keep this one clean, to just what it's doing

**Review by mkolar — APPROVED** [review]

**Pull request merged**
