### PR TITLE
Website Docs: Remove unused pages

### PR DESCRIPTION
**Pull request by BigRoy**
## Brief description

Removes unused `website/docs` pages.

## Description

I solely did a quick search manually so this might be false positives for "unused". Please double check.

### Artist Hosts Nuke - two nearly identical files, one old, one newer. Remove one?

There are also two files [`artist_hosts_nuke.md`](https://github.com/pypeclub/OpenPype/blob/develop/website/docs/artist_hosts_nuke.md) and [`artist_hosts_nuke_tut.md`](https://github.com/pypeclub/OpenPype/blob/develop/website/docs/artist_hosts_nuke_tut.md) which appear very similar. However, in some odd in-page links it links to `artist_hosts_nuke.md`.

Should we remove `artist_host_nuke.md` (older) and replace it with `artist_hosts_nuke_tut.md` (newer) and maybe even refactor that name back to `artist_host_nuke.md`?

## Testing notes:
1. please confirm these pages were indeed unused and redundant

### CODE REVIEW

**Comment by BigRoy** [comment]
This [`admin_webserver_for_webpublisher.md`](https://github.com/pypeclub/OpenPype/blob/develop/website/docs/admin_webserver_for_webpublisher.md) page also appears unused in the actual website docs. Should this be exposed? Or is that just still temporarily hidden?

**Comment by m-u-r-p-h-y** [comment]
> This [`admin_webserver_for_webpublisher.md`](https://github.com/pypeclub/OpenPype/blob/develop/website/docs/admin_webserver_for_webpublisher.md) page also appears unused in the actual website docs. Should this be exposed? Or is that just still temporarily hidden?

should probably be exposed and added to sidebars.js 
what was your plan @kalisp ?

**Comment by mkolar** [comment]
Webpublisher should actually be removed completely at this point from the repo as well and turned into a studio specific addon until it's in a better state. Right now it's quite heavily customised to a single site and it's not the best idea to have it part of the main project to be honest.

**Comment by kalisp** [comment]
Lets keep `admin_webserver_for_webpublisher.md` there for now, it will be consumed (translated into readme, I guess) in OP-2889.

**Comment by jrsndl** [comment]
File artist_hosts_nuke_tut.md includes all content from artist_host_nuke.md, so artist_host_nuke.md can be removed.
The in-page link to artist_hosts_nuke.md is a mistake.

**Comment by BigRoy** [comment]
Feel free to push changes into this PR if you have write access to OpenPype you should be able to.

**Pull request merged**
