### PR TITLE
Project Manager: Remove project button cleanup

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Brief description
Remove project does not have label so it may confuse people that it's meant for removing assets and tasks. And confimation dialog should expect project name as text instead of `delete`.

## Changes
- delete project button has label `Delete project`
- delete confirmation dialog expect to enter project name instead of `delete`

### CODE REVIEW

**Comment by BigRoy** [comment]
Can we make the project name a warning RED color? Or have the Delete button be colored red?
Somehow I feel this particular dialog doesn't raise my stress indicators as much as it should for what it is actually capable of. :)

I want to feel the urgency like in this examples:
image_processing20191014-2648-1wpej0s

**Comment by antirotor** [comment]
> And to be more safer and fun, how about making this action to require more than 1 people to be done ?

So deleting projects will look like this? 🚀 

image

We could sell the hardware then. vfx pipeline AND missile launch systems (used for project deletion)

**Comment by iLLiCiTiT** [comment]
I hope this is enough
image

**Comment by BigRoy** [comment]
Definitely looks much better to me!

**Review by 64qam — APPROVED** [review]

**Pull request merged**
