### PR TITLE
Deadline: Move module one hierarchy level higher

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Brief changes
Moved `deadline` module from default_modules folder next to base modules. 

## Changes
- moved the deadline folder to `openpype/modules/deadline`
- moved deadline repository files from `openpype/vendor/deadline` to `openpype/modules/deadline/repository`.
- `openpype/lib/abstract_submit_deadline.py` moved to `openpype/modules/deadline/abstract_submit_deadline.py`

## Notes
Affecting PRs
- https://github.com/pypeclub/OpenPype/pull/2625

## Testing notes:
1. Deadline should work as before

### CODE REVIEW

**Comment by BigRoy** [comment]
> Affecting PRs

This is not an affected PR but an issue: https://github.com/pypeclub/OpenPype/issues/2787
But this one is an affected PR: https://github.com/pypeclub/OpenPype/pull/2625

**Comment by iLLiCiTiT** [comment]
> With Deadline being its own module should we maybe also move along [vendor/deadline/custom/plugins](https://github.com/pypeclub/OpenPype/tree/develop/vendor/deadline/custom/plugins) to be closer to the module itself?

I agree. Is the plugin installed using code or it must be copied manually so it is possible just move it and change documentation?

**Comment by BigRoy** [comment]
>  or it must be copied manually so it is possible just move it and change documentation?

Those files must currently be copied manually. See [the Admin Docs for Deadline Module](https://openpype.io/docs/module_deadline/).

**Comment by BigRoy** [comment]
Didn't notice this before, but should we also move [`openpype/lib/abstract_submit_deadline.py`](https://github.com/pypeclub/OpenPype/blob/develop/openpype/lib/abstract_submit_deadline.py)?

**Review by mkolar — APPROVED** [review]

**Review by kalisp — APPROVED** [review]
Seems to work.

**Pull request merged**
