### PR TITLE
Enable write color sets on animation publish automatically

### PR DESCRIPTION
**Pull request by moonyuet**
## Brief description
This is the request from the Line. They want the "write color sets" to be on by default on the animation publish
See the ticket here: https://app.clickup.com/t/6658547/OP-3371
## Solution
Set` self.data["writeColorSets"] = True` in _create_animation.py_ in ./maya/plugins/publish folder

### CODE REVIEW

**Comment by m-u-r-p-h-y** [comment]
I'm not sure if this should be on by default, as this will affect many studios out there. Should be configurable and let them turn it on in their environment . . . and keep it off by default to keep some continuity in settings.

**Comment by moonyuet** [comment]
yes I agree. I leave the solution into the clickup first. If it is possible, just send them a script to replace the original one or just ask them to set self.data["writeColorSets"]  = True by their own.

**Review by mkolar — CHANGES_REQUESTED** [review]
This definitely needs to be added to the settings, with the default staying as it was

**Comment by moonyuet** [comment]
I have added switching on/off checkbox in Create Animation slot in the Openpype setting 
image

**Review by m-u-r-p-h-y — COMMENTED** [review]
shouldn't we approach Point Cache instance the same way as well?

It would be more consistent imo.

image

**Comment by moonyuet** [comment]
i updated the new one with the correct branch in https://github.com/pypeclub/OpenPype/pull/3582

**Pull request closed without merging**
