### PR TITLE
Make launcher and workfiles interfaces use main_task info

### PR DESCRIPTION
**Pull request by ClementHector**
Here is a simple implementation for the feature proposed in the issue #2201

This feature rely on a new field named `main_task` within the task object of an asset.
This field accept an other task name as value.

If you mark a task as a slave of another task like so, this will inform the launcher and the workfiles interface to use the workfile of the master task while keeping the information of the slave task within the Session an the environment to keep publishing normaly within this task.

### CODE REVIEW

**Comment by antirotor** [comment]
One non-techincal note - we were trying to get rid of word *master* from the code. I suggest using intead of `master task` -> `primary task` (or main task)?

**Comment by ClementHector** [comment]
> One non-techincal note - we were trying to get rid of word _master_ from the code. I suggest using intead of `master task` -> `primary task` (or main task)?

`main tasks` seem more appropriate to me.

**Comment by iLLiCiTiT** [comment]
Code looks ok but I'm not sure if the idea is right and if the key `main_task` shouldn't be more specific or totally different. It is main task only for workfile template resolving (as I understand from the code and discussion) but not for rest of workflow so it's confusing for me.

**Comment by iLLiCiTiT** [comment]
Wouldn't be better to add another key on task, like `"group"`? So you can use in templates `"{task[group]}"` instead of `"{task[name]}"` when you need it? I don't like that value of task name is changed on the fly.

**Comment by ClementHector** [comment]
This feature is no longer used in our studio, the supervisors have changed their minds. For me it is no longer useful, should I close the pull request?

**Pull request closed without merging**
