### PR TITLE
General: Collect (generative) input links

### PR DESCRIPTION
**Pull request by BigRoy**
## Brief description

This is a (currently **DRAFT**) pull request to implement specific input links used in the generation of a specific publish.

## Description

This basically implements the following code mentioned in [this comment](https://github.com/pypeclub/OpenPype/issues/2092#issuecomment-1113324596):

> https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/plugins/maya/publish/collect_inputs.py
> https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/plugins/houdini/publish/collect_inputs.py
> https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/plugins/fusion/publish/collect_inputs.py

Note that the [Houdini code actually already exists in the OpenPype code base](https://github.com/pypeclub/OpenPype/blob/e93558f961c32615b36177f0e2a212ed59f22e24/openpype/hosts/houdini/plugins/publish/collect_inputs.py) and thus is **NOT** in this PR.

## TODO

- [x] Collectors for Maya, Fusion, Houdini 
- [ ] Make sure the data link type is correct, either `generative` or `reference` depending on the publish type
- [x] Actually integrate the data into the database

To mark the input data link type correctly we'd probably need to allow the Extractors define that relationship. For example a `mayaScene` extractor would mark the input links as `reference` (published data will still needs those references) whereas e.g. an alembic cache would mark its inputs as just `generative` (references are just used to generate output that works standalone) 

## Additional info

This relates to:
- #2509 
- #2092 
- [OpenPype Asset Dependencies Miro Board](https://miro.com/app/board/o9J_lAB4oQ0=/)
- [OpenPype Discord Input Links generation thread](https://discord.com/channels/517362899170230292/1006207855503876156)

## Testing notes:
1. Open any of Maya, Fusion, Houdini
2. Load something with the loader
3. Create/Publish something with the loaded content used as input.
4. (Optional) Also test with loading something and NOT using that as input. This content should _not_ be collected for the instance.
5. Publish.
6. Check the input links / dependencies.

### CODE REVIEW

**Comment by BigRoy** [comment]
Current example of "Workfile" links provided by @kalisp:

openpype_input_links_workfiles_example_by_kalisp

Most input links for publishes and containers "used in the generation of that publish" will likely be **generative** by default but some (like a `mayaScene`) will still be dependent on the input references/used files and thus will be of link type **reference** as described on the [Miro board](https://miro.com/app/board/o9J_lAB4oQ0=/)

afbeelding

I was thinking of having the Extractor or a family setting whether the input links are Generative or Reference, with Generative being the default due to being most common?

**Comment by BigRoy** [comment]
Current code should work as expected. 

Only thing to note still is that [ALL these links will be `generative` due to how `inputVersions` are linked in the Integrate Input Links integrator](https://github.com/pypeclub/OpenPype/blob/develop/openpype/plugins/publish/integrate_inputlinks.py#L77-L84). Technically for a `mayaScene` publish this would be "incorrect" since the input versions would actually be `reference` links because the publishes maya scene would still need the original 'references' to exist, etc.

**Comment by BigRoy** [comment]
We're using this in production now!

However I've noticed that input versions don't make their way into published renderlayers from e.g Maya through Deadline. That's now fixed with https://github.com/pypeclub/OpenPype/pull/3629/commits/eab14fc5e9204126554e8be5898010e0db0398ca however that'll include the input versions with each AOV. For many input ids and many AOV this could quickly bloat the `.json` file quite a bit. Another option would be instead to store it outside of the instance skeleton data and just store it globally in the metadata json and then we assume each AOV will share the same input versions? (However I'm not sure how true that logic is for potential other hosts/submissions supporting metadata.json files)

Also, I'm mapping the `inputVersions` objectIds to `str` so the `json.dump` works nicely. Instead of doing that we could also use a custom JSON encoder which forces all objectIds to become str anyway. But I felt explicitly for this value made more sense.

**Comment by antirotor** [comment]
Thanks, this looks great! Can't wait to test it. One note about the AOV/input links - I was thinking hard about the uses in different DCCs and I think that this applies. In one deadline submission - ie. connected to one json file, we have output from the same data, after effects composition, harmony scene or maya render layer. There might be of course exceptions if you go to big enough detail - like should AOV of lightgroup have input link to referenced light rig even if it doesn't include them, and so on.

**Comment by BigRoy** [comment]
> There might be of course exceptions if you go to big enough detail - like should AOV of lightgroup have input link to referenced light rig even if it doesn't include them, and so on.

I love you. That's a perfect use case where an AOV could differ.

**Comment by BigRoy** [comment]
Would be great if this could see some testing soon!

**Review by antirotor — APPROVED** [review]
I've tested it, not in depth but so far it works and it doesn't break publishing so I think it is safe to merge. I've found gaps in workfile links but those are no concern of this PR

**Comment by BigRoy** [comment]
>  I've found gaps in workfile links.

Could you elaborate?

**Comment by antirotor** [comment]
> Could you elaborate?

it's actually difficult question. If you publish model and with it workfile, should that published workfile have outgoing link to the model? That's what happened to me - that published workfiles are not linking to published stuff.

**Comment by mkolar** [comment]
> > Could you elaborate?
> 
> it's actually difficult question. If you publish model and with it workfile, should that published workfile have outgoing link to the model? That's what happened to me - that published workfiles are not linking to published stuff.

Ideally that should be the case, removing as many workfile dependencies as possible of course. But I'd personally merge this and continue that conversation in an improvement issue. This in itself will be a massive improvement right away.

**Review by mkolar — APPROVED** [review]

**Comment by BigRoy** [comment]
> it's actually difficult question. If you publish model and with it workfile, should that published workfile have outgoing link to the model? That's what happened to me - that published workfiles are not linking to published stuff.

Wait a second - for me it does that! 

afbeelding

You are saying a workfile is not showing its outputs?
Are you seeing any outputs whatsoever?

**Comment by BigRoy** [comment]
@antirotor Could you confirm [my last comment](https://github.com/pypeclub/OpenPype/pull/3629#issuecomment-1243870103)?

Would love to resolve and get this PR merged.

**Comment by mkolar** [comment]
We can merge this. It didn't work for Ondrej, but it did for me. I reckon we can iron it out over time if we find the cause.

**Pull request merged**
