### PR TITLE
Deadline: Tweak validate expected files behavior

### PR DESCRIPTION
**Pull request by BigRoy**
## Brief description

I'd like to propose some tweaks to the validate expected files behavior for Deadline. I started looking into this since the log wasn't too user friendly for missing files as it would report it unsorted from a `set` and thus it was hard to see what part of the sequence was missing.

Then I also noticed some other things that felt off when glancing over the code. I'm opening this **draft PR** to discuss implementation details as I'm not sure how others originally used it.

Here are the tweaks I've tried to make:

- Improve reported missing files by logging them sorted
- Always check for use override, since updated Job frame list might be longer than initial frame list.
- Check only for missing files instead of difference in files - allow other files to exist
- Add a raised error if `file_name_template` could not be parsed - since that would be problematic if it happens?
  - Are there cases where `file_name_template` should not be parsable? E.g. can one submit a single frame to render without a frame number in it at all? Because if that would be considered valid then erroring out here would break those cases.

#### Testing notes

- Current draft code changes are untested. I'd like to first discuss the tweaks and clean up where needed.

### CODE REVIEW

**Comment by BigRoy** [comment]
> - Always check for use override, since updated Job frame list might be longer than initial frame list.

Actually that should've worked before too because it did a plain `set.difference` check at first, so if more files were rendered the difference would have still been detected. However if the original job had e.g. rendered frame 1-5 of a job which was set to render 1-100. Then the user updates the frame list in deadline to 50-100 because he figured he didn't need the beginning then before it wouldn't have worked.

Also, say the render job was originally 1-10, it fully rendered. Then the job frame list was updated to: 10-20 because originally the user did something wrong. Before it would never have considered the new user override. With these changes implemented, it would work.

**Comment by iLLiCiTiT** [comment]
I've tried to merge last develop (with this https://github.com/pypeclub/OpenPype/pull/2789) but it didn't resolve changes properly.

**Comment by BigRoy** [comment]
Let me take a look @iLLiCiTiT

**Comment by BigRoy** [comment]
@iLLiCiTiT this should be good now.

**Comment by BigRoy** [comment]
Hmm. I'm not sure if this being force pushed will work nice with merging and other PRs. Anyone know more?

**Comment by iLLiCiTiT** [comment]
> I'm not sure if this being force pushed will work nice with merging and other PRs.

It should be ok. Force push replaces branch commits without deleting the branch.

**Comment by BigRoy** [comment]
Then would be nice if someone could give this a go - it should be ready to merge.

**Review by kalisp — APPROVED** [review]
Looks good, tested in AE, Nuke. Removed some expected, added some unexpected files.

**Pull request merged**
